# -*- coding: utf-8 -*-
"""Delta-Neutral Portfolio Construction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
from dataclasses import dataclass
from typing import List, Optional
import warnings

@dataclass
class OptionPosition:
    weight: float
    K: float
    T: float
    option_type: str
    sigma_imp: float

class DeltaNeutralBook:
    def __init__(self, S: float, r: float, q: float=0.0):
        self.S = S
        self.r = r
        self.q = q
        self.positions: List[OptionPosition] = []
        self.hedge_shares: float = 0.0

    def add_position(self, pos: OptionPosition):
        self.positions.append(pos)

    def bs_greeks(self, S, K, T, sigma, q, r, otype):
        if T < 1e-8:
            return {
                'delta': float(S > K) if otype=='call' else -float(S < K),
                'gamma': 0.0,
                'vega': 0.0,
                'theta': 0.0,
                'price': max(S-K, 0) if otype=='call' else max(K-S, 0)
            }

        sqT = np.sqrt(T)
        d1 = (np.log(S/K) + (r - q + 0.5*sigma**2)*T) / (sigma * sqT)
        d2 = d1 - sigma * sqT
        nd1 = norm.pdf(d1)
        disc_q = np.exp(-q*T)
        disc_r = np.exp(-r*T)

        if otype == 'call':
            price = S*disc_q*norm.cdf(d1) - K*disc_r*norm.cdf(d2)
            delta = disc_q*norm.cdf(d1)
        else:
            price = K*disc_r*norm.cdf(-d2) - S*disc_q*norm.cdf(-d1)
            delta = -disc_q*norm.cdf(-d1)

        gamma = disc_q*nd1 / (S*sigma*sqT)
        vega = S * disc_q * nd1 * sqT / 100  # per 1% vol

        theta = (-(S * disc_q * nd1 * sigma) / (2 * sqT)
                 - r * K * disc_r * (norm.cdf(d2) if otype == 'call' else -norm.cdf(-d2))
                 + q * S * disc_q * (norm.cdf(d1) if otype == 'call' else -norm.cdf(-d1))) / 365

        return {
            'price': price,
            'delta': delta,
            'gamma': gamma,
            'vega': vega,
            'theta': theta
        }

    def portfolio_greeks(self, S: Optional[float] = None):
        """Aggregate portfolio greeks at spot S."""
        S = S or self.S
        agg = {'price': 0., 'delta': 0., 'gamma': 0., 'vega': 0., 'theta': 0.}
        for pos in self.positions:
            g = self.bs_greeks(S, pos.K, pos.T, pos.sigma_imp, self.q, self.r, pos.option_type)
            for k in agg:
                agg[k] += pos.weight * g[k]
        # Include existing hedge
        agg['delta'] += self.hedge_shares  # shares have delta = 1 each
        return agg

    def delta_hedge(self, S: Optional[float] = None, use_futures: bool = False, futures_tenor: Optional[float] = None, verbose: bool = True) -> dict:
        S = S or self.S
        g = self.portfolio_greeks(S)
        option_delta = g['delta'] - self.hedge_shares  # remove hedge contribution

        # Hedge trade needed
        delta_required = -option_delta
        hedge_trade = delta_required - self.hedge_shares

        if use_futures and futures_tenor is not None:
            fwd_factor = np.exp((self.r - self.q) * futures_tenor)
            futures_needed = delta_required / fwd_factor
            futures_trade = futures_needed - self.hedge_shares / fwd_factor
            if verbose:
                print(f"Futures hedge: {futures_needed:+.4f} contracts (trade: {futures_trade:+.4f})")
            self.hedge_shares = futures_needed * fwd_factor
        else:
            self.hedge_shares = delta_required
            if verbose:
                print(f"Stock hedge: {delta_required:+.4f} shares (trade: {hedge_trade:+.4f})")

        final_g = self.portfolio_greeks(S)
        if verbose:
            print(f"\n--- Portfolio Greeks after hedge ---")
            for k, v in final_g.items():
                print(f"  {k:8s}: {v:+10.6f}")
        return {
            'greeks': final_g,
            'hedge_trade': hedge_trade,
            'total_hedge': self.hedge_shares
        }

# Initialize book
book = DeltaNeutralBook(S=100, r=0.05, q=0.01)

# Long 100 ATM straddles (1 call + 1 put per contract, 100 contracts)
n = 100
book.add_position(OptionPosition(n, K=100, T=0.5, option_type='call', sigma_imp=0.22))
book.add_position(OptionPosition(n, K=100, T=0.5, option_type='put', sigma_imp=0.22))

# Short 50 OTM calls (a covered overwrite)
book.add_position(OptionPosition(-50, K=110, T=0.5, option_type='call', sigma_imp=0.20))

print("=== Pre-Hedge Greeks ===")
g0 = book.portfolio_greeks()
for k, v in g0.items():
    print(f"  {k}: {v:+.4f}")

print("\n=== Executing Delta Hedge ===")
result = book.delta_hedge(verbose=True)

# Verify delta neutral
assert abs(result['greeks']['delta']) < 1e-10, "Hedge failed!"
print(f"\nPost-hedge delta: {result['greeks']['delta']:.2e}")
print(f"Net gamma exposure: {result['greeks']['gamma']:+.4f}")
print(f"Net vega exposure: {result['greeks']['vega']:+.4f}")

