# -*- coding: utf-8 -*-
"""Dynamic Hedging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
from typing import Tuple

class DynamicHedgingSimulator:
    def __init__(self, S0, K, T, r, sigma_imp, q=0.0, sigma_real=None, seed=42):
        self.S0 = S0
        self.K = K
        self.T = T
        self.r = r
        self.iv = sigma_imp
        self.rv = sigma_real if sigma_real is not None else sigma_imp
        self.q = q
        np.random.seed(seed)

    def _bs(self, S, K, T, r, sigma, q, otype='call'):
        if T < 1e-8:
            p = max(S - K, 0) if otype == 'call' else max(K - S, 0)
            return dict(price=p, delta=float(S > K if otype == 'call' else S < K),
                        gamma=0., vega=0., theta=0.)
        sqT = np.sqrt(T)
        d1 = (np.log(S / K) + (r - q + .5 * sigma ** 2) * T) / (sigma * sqT)
        d2 = d1 - sigma * sqT
        nd1 = norm.pdf(d1)
        dq = np.exp(-q * T)
        dr = np.exp(-r * T)
        if otype == 'call':
            price = S * dq * norm.cdf(d1) - K * dr * norm.cdf(d2)
            delta = dq * norm.cdf(d1)
        else:
            price = K * dr * norm.cdf(-d2) - S * dq * norm.cdf(-d1)
            delta = -dq * norm.cdf(-d1)
        gamma = dq * nd1 / (S * sigma * sqT)
        vega = S * dq * nd1 * sqT / 100
        theta = (-(S * dq * nd1 * sigma) / (2 * sqT)
                 - (r * K * dr * (norm.cdf(d2) if otype == 'call' else norm.cdf(-d2)))
                 + (q * S * dq * (norm.cdf(d1) if otype == 'call' else norm.cdf(-d1)))) / 365
        return dict(price=price, delta=delta, gamma=gamma, vega=vega, theta=theta)

    def simulate_path(self, n_steps: int = 252, otype: str = 'call') -> dict:
        dt = self.T / n_steps
        sqdt = np.sqrt(dt)
        Z = np.random.randn(n_steps)
        log_ret = (self.r - self.q - .5 * self.rv ** 2) * dt + self.rv * sqdt * Z
        S = np.empty(n_steps + 1)
        S[0] = self.S0
        S[1:] = self.S0 * np.exp(np.cumsum(log_ret))
        times = np.linspace(0, self.T, n_steps + 1)
        taus = self.T - times

        greeks = [self._bs(S[i], self.K, max(taus[i], 1e-8), self.r, self.iv, self.q, otype)
                  for i in range(n_steps + 1)]

        prices = np.array([g['price'] for g in greeks])
        deltas = np.array([g['delta'] for g in greeks])
        gammas = np.array([g['gamma'] for g in greeks])
        thetas = np.array([g['theta'] for g in greeks])

        dV = np.diff(prices)
        dS = np.diff(S)
        dt_arr = np.full(n_steps, dt)

        delta_pnl = deltas[:-1] * dS
        gamma_pnl = 0.5 * gammas[:-1] * dS ** 2
        theta_pnl = thetas[:-1] * dt_arr * 365
        hedge_pnl = -deltas[:-1] * dS

        net_pnl_step = dV + hedge_pnl
        gamma_realized = 0.5 * gammas[:-1] * (dS ** 2 - self.iv ** 2 * S[:-1] ** 2 * dt_arr)
        theta_net = -0.5 * gammas[:-1] * self.iv ** 2 * S[:-1] ** 2 * dt_arr

        return {
            'S': S,
            'times': times,
            'greeks': greeks,
            'dV': dV,
            'dS': dS,
            'delta_pnl': delta_pnl,
            'gamma_pnl': gamma_pnl,
            'theta_pnl': theta_pnl,
            'net_pnl_step': net_pnl_step,
            'gamma_realized': gamma_realized,
            'cum_pnl': np.cumsum(net_pnl_step),
            'total_pnl': net_pnl_step.sum(),
            'total_gamma_pnl': gamma_realized.sum(),
        }

    def monte_carlo(self, n_paths=5000, n_steps=252, otype='call') -> dict:
        """Run Monte Carlo of dynamic hedging P&L."""
        results = [self.simulate_path(n_steps, otype) for _ in range(n_paths)]
        pnls = np.array([r['total_pnl'] for r in results])
        return {
            'pnl_distribution': pnls,
            'mean': pnls.mean(),
            'std': pnls.std(),
            'sharpe': pnls.mean() / pnls.std() * np.sqrt(252),
            'p25': np.percentile(pnls, 25),
            'p75': np.percentile(pnls, 75),
            'paths': results[:10]}

sim = DynamicHedgingSimulator(S0=100, K=100, T=0.25, r=0.05, sigma_imp=0.20, sigma_real=0.25)
mc = sim.monte_carlo(n_paths=3000, n_steps=63)
print(f"Mean P&L: ${mc['mean']:.4f}")
print(f"Std P&L: ${mc['std']:.4f}")
print(f"Sharpe: {mc['sharpe']:.3f}")
print(f"25th pctile: ${mc['p25']:.4f}")
print(f"75th pctile: ${mc['p75']:.4f}")

