# -*- coding: utf-8 -*-
"""Hedging Frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm

def simulate_fixed_time_hedge(S0, K, T, r, iv, rv, n_steps, tc_bps=10, seed=None):
    if seed is not None:
        np.random.seed(seed)
    dt = T / n_steps
    sqdt = np.sqrt(dt)
    tc = tc_bps / 10000

    S = S0
    hedge = 0.0
    cash = 0.0
    pnl_gamma = 0.0
    total_tc = 0.0
    n_trades = 0

    def delta(S, tau, sig):
        if tau < 1e-8:
            return float(S > K)
        d1 = (np.log(S / K) + (r + 0.5 * sig ** 2) * tau) / (sig * np.sqrt(tau))
        return norm.cdf(d1)

    def gamma_fn(S, tau, sig):
        if tau < 1e-8:
            return 0.0
        d1 = (np.log(S / K) + (r + 0.5 * sig ** 2) * tau) / (sig * np.sqrt(tau))
        return norm.pdf(d1) / (S * sig * np.sqrt(tau))

    for step in range(n_steps):
        tau = T - step * dt
        Z = np.random.randn()
        S_new = S * np.exp((r - 0.5 * rv ** 2) * dt + rv * sqdt * Z)
        dS = S_new - S

        G = gamma_fn(S, tau, iv)
        pnl_gamma += 0.5 * G * dS ** 2

        S = S_new
        tau -= dt
        d_new = delta(S, max(tau, 0), iv)
        d_trade = d_new - hedge
        trade_cost = tc * abs(d_trade) * S
        cash -= d_trade * S + trade_cost
        hedge = d_new
        total_tc += trade_cost
        n_trades += 1

    payoff = max(S - K, 0)
    pnl_total = payoff + hedge * S + cash - pnl_gamma
    return {
        'pnl': pnl_gamma - total_tc,
        'gamma_pnl': pnl_gamma,
        'tc': total_tc,
        'n_trades': n_trades
    }

def simulate_delta_band_hedge(S0, K, T, r, iv, rv, epsilon, max_steps=10000, tc_bps=10, seed=None):
    if seed is not None:
        np.random.seed(seed)
    dt_fine = T / max_steps
    sqdt = np.sqrt(dt_fine)
    tc = tc_bps / 10000

    def delta(S, tau):
        if tau < 1e-8:
            return float(S > K)
        d1 = (np.log(S / K) + (r + 0.5 * iv ** 2) * tau) / (iv * np.sqrt(tau))
        return norm.cdf(d1)

    def gamma_fn(S, tau):
        if tau < 1e-8:
            return 0.0
        d1 = (np.log(S / K) + (r + 0.5 * iv ** 2) * tau) / (iv * np.sqrt(tau))
        return norm.pdf(d1) / (S * iv * np.sqrt(tau))

    S = S0
    tau = T
    hedge = delta(S, tau)
    pnl_g = 0.0
    total_tc = 0.0
    n_trades = 1

    for step in range(max_steps):
        Z = np.random.randn()
        S_new = S * np.exp((r - 0.5 * rv ** 2) * dt_fine + rv * sqdt * Z)
        dS = S_new - S
        G = gamma_fn(S, tau)
        pnl_g += 0.5 * G * dS ** 2
        S = S_new
        tau = max(tau - dt_fine, 0)

        d_new = delta(S, tau)
        if abs(d_new - hedge) > epsilon or tau < 1e-8:
            d_trade = d_new - hedge
            total_tc += tc * abs(d_trade) * S
            hedge = d_new
            n_trades += 1

    return {
        'pnl': pnl_g - total_tc,
        'gamma_pnl': pnl_g,
        'tc': total_tc,
        'n_trades': n_trades
    }

N_runs = 2000
params = dict(S0=100, K=100, T=0.25, r=0.05, iv=0.20, rv=0.22)

print(f"{'Method': <25} {'Mean P&L': >10} {'Std P&L': >10} {'Mean TC': >10} {'Avg Trades': >12}")
print("-" * 70)

for N in [5, 13, 52, 252]:
    results = [simulate_fixed_time_hedge(**params, n_steps=N, tc_bps=10, seed=i) for i in range(N_runs)]
    pnls = np.array([r['pnl'] for r in results])
    tcs = np.array([r['tc'] for r in results])
    ntr = np.mean([r['n_trades'] for r in results])
    print(f"Fixed-time N={N: <4} {pnls.mean(): >10.4f} {pnls.std(): >10.4f} {tcs.mean(): >10.4f} {ntr: >12.1f}")

for eps in [0.05, 0.02, 0.01]:
    results = [simulate_delta_band_hedge(**params, epsilon=eps, tc_bps=10, seed=i) for i in range(N_runs)]
    pnls = np.array([r['pnl'] for r in results])
    tcs = np.array([r['tc'] for r in results])
    ntr = np.mean([r['n_trades'] for r in results])
    print(f"Delta-band eps={eps: <5} {pnls.mean(): >10.4f} {pnls.std(): >10.4f} {tcs.mean(): >10.4f} {ntr: >12.1f}")

