# -*- coding: utf-8 -*-
"""Gamma Scalping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import pandas as pd
import matplotlib.pyplot as plt

class GammaScalper:
    def __init__(self, S0, K, T, iv, r=0.05, q=0.0, n_contracts=100, multiplier=100):
        self.S0 = S0
        self.K = K
        self.T = T
        self.iv = iv
        self.r = r
        self.q = q
        self.n_contracts = n_contracts
        self.multiplier = multiplier
        self.scale = n_contracts * multiplier

    def _greeks(self, S, tau):
        if tau < 1e-8:
            return {'delta': float(S > self.K), 'gamma': 0., 'theta': 0., 'price': max(S - self.K, 0)}
        sig = self.iv
        sqT = np.sqrt(tau)
        d1 = (np.log(S / self.K) + (self.r - self.q + .5 * sig ** 2) * tau) / (sig * sqT)
        d2 = d1 - sig * sqT
        nd1 = norm.pdf(d1)
        dq = np.exp(-self.q * tau)
        dr = np.exp(-self.r * tau)

        call_price = S * dq * norm.cdf(d1) - self.K * dr * norm.cdf(d2)
        put_price = self.K * dr * norm.cdf(-d2) - S * dq * norm.cdf(-d1)
        delta = dq * (norm.cdf(d1) - norm.cdf(-d1))
        gamma = 2 * dq * nd1 / (S * sig * sqT)
        theta = (2 * (-(S * dq * nd1 * sig) / (2 * sqT)) - self.r * self.K * dr * (norm.cdf(d2) + norm.cdf(-d2))
                 + self.q * S * dq * (norm.cdf(d1) + norm.cdf(-d1))) / 365
        price = call_price + put_price
        dgamma = 0.5 * gamma * S ** 2
        return {'delta': delta, 'gamma': gamma, 'dgamma': dgamma, 'theta': theta, 'price': price}

    def backtest(self, spot_path: np.ndarray, dt: float = 1/252, hedge_freq: int = 1, tc_bps: float = 5.0, verbose: bool = False) -> pd.DataFrame:
        n_steps = len(spot_path) - 1
        tc = tc_bps / 10000
        records = []

        g0 = self._greeks(self.S0, self.T)
        hedge_position = -g0['delta'] * self.scale
        last_hedge_step = 0

        for step in range(n_steps):
            S_prev = spot_path[step]
            S_curr = spot_path[step + 1]
            tau = self.T - (step + 1) * dt
            dS = S_curr - S_prev
            ret = dS / S_prev

            g_prev = self._greeks(S_prev, self.T - step * dt)
            g_curr = self._greeks(S_curr, max(tau, 1e-8))

            option_pnl = (g_curr['price'] - g_prev['price']) * self.scale

            hedge_pnl = hedge_position * dS

            gamma_pnl_attr = 0.5 * g_prev['gamma'] * dS ** 2 * self.scale
            theta_pnl_attr = g_prev['theta'] * dt * 365 * self.scale
            variance_edge = 0.5 * g_prev['dgamma'] * (ret ** 2 - self.iv ** 2 * dt) * self.scale

            trade_cost = 0.0
            if (step - last_hedge_step) >= hedge_freq or tau < 1e-8:
                new_hedge = -g_curr['delta'] * self.scale
                trade = new_hedge - hedge_position
                trade_cost = tc * abs(trade) * S_curr
                hedge_position = new_hedge
                last_hedge_step = step

            net_step_pnl = option_pnl + hedge_pnl - trade_cost
            records.append({
                'step': step + 1,
                'S': S_curr,
                'tau': tau,
                'ret': ret,
                'option_pnl': option_pnl,
                'hedge_pnl': hedge_pnl,
                'gamma_attr': gamma_pnl_attr,
                'theta_attr': theta_pnl_attr,
                'variance_edge': variance_edge,
                'trade_cost': trade_cost,
                'net_pnl': net_step_pnl,
                'dgamma': g_prev['dgamma'] * self.scale,
            })

        df = pd.DataFrame(records)
        df['cum_pnl'] = df['net_pnl'].cumsum()
        df['cum_gamma'] = df['gamma_attr'].cumsum()
        df['cum_theta'] = df['theta_attr'].cumsum()
        df['cum_tc'] = df['trade_cost'].cumsum()
        return df

np.random.seed(12)
T = 63/252
n = 63
dt = 1/252
rv = 0.25
iv = 0.20
S0 = 100

log_ret = (0.05 - 0.5 * rv ** 2) * dt + rv * np.sqrt(dt) * np.random.randn(n)
path = S0 * np.exp(np.r_[0, log_ret.cumsum()])

scalper = GammaScalper(S0=S0, K=S0, T=T, iv=iv, r=0.05)
df = scalper.backtest(path, dt=dt, hedge_freq=1, tc_bps=5)

print("\n=== Gamma Scalping P&L Attribution ===")
print(f"Total Net P&L: ${df['net_pnl'].sum(): >10.2f}")
print(f"Total Gamma P&L: ${df['gamma_attr'].sum(): >10.2f}")
print(f"Total Theta P&L: ${df['theta_attr'].sum(): >10.2f}")
print(f"Total TC: ${df['trade_cost'].sum(): >10.2f}")
print(f"Variance Edge: ${df['variance_edge'].sum(): >10.2f}")
print(f"\nAvg Daily Vol (real): {np.std(df['ret']) * np.sqrt(252) * 100:.2f}%")
print(f"Implied Vol: {iv * 100:.2f}%")

