# -*- coding: utf-8 -*-
"""Path dependency in Gamma Scalping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm, skew, kurtosis
import matplotlib.pyplot as plt
from collections import defaultdict

def gamma_scalp_path_study(S0=100, K=100, T=63/252, r=0.05, iv=0.20, rv=0.22, n_paths=5000, n_steps=63, seed=12):
    np.random.seed(seed)
    dt = T / n_steps
    sqdt = np.sqrt(dt)

    def greek(S, tau, sig=iv):
        if tau < 1e-8:
            return dict(gamma=0., dgamma=0., delta=float(S > K))
        d1 = (np.log(S / K) + (r + 0.5 * sig ** 2) * tau) / (sig * np.sqrt(tau))
        nd1 = norm.pdf(d1)
        gam = nd1 / (S * sig * np.sqrt(tau))
        return dict(gamma=gam, dgamma=0.5 * gam * S ** 2, delta=norm.cdf(d1))

    results = defaultdict(list)

    for path_idx in range(n_paths):
        Z = np.random.randn(n_steps)
        log_ret = (r - 0.5 * rv ** 2) * dt + rv * sqdt * Z
        S_arr = np.empty(n_steps + 1)
        S_arr[0] = S0
        S_arr[1:] = S0 * np.exp(np.cumsum(log_ret))
        times = np.linspace(0, T, n_steps + 1)
        taus = T - times

        # Classify path
        S_final = S_arr[-1]
        path_range = S_arr.max() - S_arr.min()
        path_return = (S_final - S0) / S0
        path_type = 'neutral'
        if abs(path_return) > 0.05:
            path_type = 'trending_up' if path_return > 0 else 'trending_down'
        elif path_range < 0.03 * S0:
            path_type = 'low_rv'
        else:
            path_type = 'mean_reverting'

        pnl_gamma = 0.0
        pnl_theta = 0.0
        wt_rv_num = 0.0
        wt_rv_den = 0.0

        for step in range(n_steps):
            g = greek(S_arr[step], max(taus[step], 1e-8))
            dS = S_arr[step + 1] - S_arr[step]
            ret = dS / S_arr[step]
            pnl_gamma += g['dgamma'] * (ret ** 2 - iv ** 2 * dt)
            pnl_theta -= g['dgamma'] * iv ** 2 * dt
            wt_rv_num += g['dgamma'] * ret ** 2
            wt_rv_den += g['dgamma']

        wt_rv = np.sqrt(wt_rv_num / max(wt_rv_den, 1e-12) / dt) if wt_rv_den > 0 else 0.0

        results['path_type'].append(path_type)
        results['pnl'].append(pnl_gamma)
        results['S_final'].append(S_final)
        results['path_return'].append(path_return)
        results['wt_rv'].append(wt_rv)

    # Summary by path type
    types = set(results['path_type'])
    print(f"{'Path Type': <20} {'Count': >6} {'Mean P&L': >10} {'Std P&L': >10} {'Avg WtRV %': >12}")
    print("-" * 62)
    for ptype in sorted(types):
        mask = [i for i, t in enumerate(results['path_type']) if t == ptype]
        pnls = np.array([results['pnl'][i] for i in mask])
        wrvs = np.array([results['wt_rv'][i] for i in mask])
        print(f"{ptype: <20} {len(mask): >6} {pnls.mean(): >10.4f} {pnls.std(): >10.4f} {wrvs.mean() * 100: >11.2f}%")

    return results

res = gamma_scalp_path_study(rv=0.24, iv=0.20, n_paths=8000)

