# -*- coding: utf-8 -*-
"""Transaction Cost Analysis Adjusting Gamma Scalping Framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
from scipy.optimize import minimize_scalar
import matplotlib.pyplot as plt

class TCGammaScalper:
  def __init__ (self, S0, K, T, iv, rv, r =0.05, q =0.0, tc_bps =5.0, impact_coeff =0.5, daily_volume =1e7, n_contracts =100 , mult =100):
    self . S0 = S0 ; self . K = K ; self . T = T
    self . iv = iv ; self . rv = rv ; self . r = r ; self . q = q
    self . k = tc_bps / 10000
    self . eta = impact_coeff
    self . V_daily = daily_volume
    self . scale = n_contracts * mult
    d1 = ( np . log ( S0 / K ) + ( r + 0.5* iv **2) * T ) / ( iv * np . sqrt ( T ) )
    gamma = norm . pdf ( d1 ) / ( S0 * iv * np . sqrt ( T ) )
    self . dgamma = 0.5 * gamma * S0 **2 * self . scale
    self . gamma = gamma * self . scale

  def pnl_stats(self, N:int):
    dt = self . T / N
    mean_pnl = self . dgamma * ( self . rv **2 - self . iv **2) * self . T
    std_pnl = self . dgamma * self . rv **2 * self . T * np . sqrt (2/ N )
    avg_delta_change = self . gamma * self . S0 * self . rv * np . sqrt(2* dt / np . pi )
    tc_linear = self.k * avg_delta_change * N
    tc_impact = self.eta * self.rv*np.sqrt(avg_delta_change / self . V_daily ) * avg_delta_change * N
    total_tc = tc_linear + tc_impact
    net_mean = mean_pnl - total_tc
    sharpe = net_mean / std_pnl * np . sqrt (252) if std_pnl > 0 else 0

    return dict (N =N , mean_pnl = mean_pnl , std_pnl = std_pnl ,
               tc = total_tc , net_mean = net_mean , sharpe = sharpe , break_even_vol = np . sqrt ( self . iv **2 + total_tc /( self . dgamma * self . T ) )*100)


  def optimal_N ( self , N_range =(1 , 2000) ) :
    def neg_sharpe ( N ) :
      N_int = max (1 , int ( N ) )
      return - self.pnl_stats ( N_int )["sharpe"]
    res = minimize_scalar( neg_sharpe , bounds = N_range , method ="bounded")
    return int ( res . x ) , self . pnl_stats (int( res . x ) )

  def sweep ( self , N_values = None ) :
    if N_values is None :
      N_values = [1 , 2 , 4 , 13 , 26 , 52 , 63 , 126 , 252 , 504 , 1008]
      rows = [ self . pnl_stats ( N ) for N in N_values ]
      return rows


scalper = TCGammaScalper ( S0 =100 , K =100 , T =0.25 , iv =0.20 , rv =0.25 , tc_bps =5.0 , n_contracts =500 , mult =100)
N_opt , stats_opt = scalper . optimal_N ()
print ( f" Optimal hedging frequency : { N_opt } re - hedges ")
print ( f" Net Mean P&L: ${ stats_opt ["net_mean"]: ,.2f}")
print ( f" Std Dev P&L: ${ stats_opt ["std_pnl"]: ,.2f}")
print ( f" Net Sharpe : { stats_opt ["sharpe"]:.3f}")
print ( f" Break - even vol : { stats_opt [ "break_even_vol"]:.2f}%")
print ( f"\n{"N": >6} {"Mean": >10} {"TC": >10} {"Net": >10} {"Sharpe": >8} {"BE Vol %": >8}")
for row in scalper . sweep () :
  print ( f"{row ["N"]: >6} {row ["mean_pnl"]: >10.1f} {row["tc"]: >10.1f} " f"{row ["net_mean"]: >10.1f} {row["sharpe"]: >8.3f} " f"{row ["break_even_vol"]: >8.2f}%")

