# -*- coding: utf-8 -*-
"""HAR-RV Volatility Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import warnings; warnings.filterwarnings('ignore')

class HARRVModel:
    def __init__(self, D_lag=1, W_lag=5, M_lag=22):
        self.D = D_lag; self.W = W_lag; self.M = M_lag
        self.model = LinearRegression()

    def _build_features(self, rv_series: np.ndarray) -> np.ndarray:
        n = len(rv_series)
        max_lag = self.M
        X = []
        for t in range(max_lag, n - 1):
            rv_d = rv_series[t]
            rv_w = rv_series[t - self.W + 1: t + 1].mean()
            rv_m = rv_series[t - self.M + 1: t + 1].mean()
            X.append([rv_d, rv_w, rv_m])
        return np.array(X)

    def fit(self, rv_series: np.ndarray):
        X = self._build_features(rv_series)
        y = rv_series[self.M + 1:]
        self.model.fit(X, y)
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        return self

    def predict_next(self, rv_series: np.ndarray) -> float:
        rv_d = rv_series[-1]
        rv_w = rv_series[-self.W:].mean()
        rv_m = rv_series[-self.M:].mean()
        return self.model.predict([[rv_d, rv_w, rv_m]])[0]

    def vol_signal(self, rv_series, iv_series, tc_threshold=0.02):
        pred_rv = self.predict_next(rv_series)
        pred_vol = np.sqrt(pred_rv * 252)
        iv_ann = iv_series[-1]
        edge = pred_vol - iv_ann
        if edge > tc_threshold:
            return +1, pred_vol, edge
        elif edge < -tc_threshold:
            return -1, pred_vol, edge
        else:
            return 0, pred_vol, edge

np.random.seed(12)
n = 500
omega, alpha, beta = 0.00001, 0.08, 0.91
sigma2 = np.zeros(n); sigma2[0] = omega / (1 - alpha - beta)
eps = np.zeros(n)
for t in range(1, n):
    eps[t] = np.sqrt(sigma2[t-1]) * np.random.randn()
    sigma2[t] = omega + alpha * eps[t-1]**2 + beta * sigma2[t-1]

rv_daily = sigma2
iv_daily = np.sqrt(sigma2 * 252) * 1.04

model = HARRVModel()
model.fit(rv_daily[:400])
print(f"HAR coefficients: D={model.coef_[0]:.3f}, W={model.coef_[1]:.3f}, M={model.coef_[2]:.3f}")

preds = []
for t in range(400, 490):
    p = model.predict_next(rv_daily[t-22: t+1])
    preds.append(np.sqrt(p * 252))

actual_vol = np.sqrt(rv_daily[401:491] * 252)
rmse = np.sqrt(mean_squared_error(actual_vol, preds))
print(f"Out-of-sample RMSE (vol): {rmse * 100:.4f}%")

signal, pred_vol, edge = model.vol_signal(rv_daily[478:501], iv_daily[478:501])
print(f"\nCurrent signal: {signal:+d}")
print(f"Predicted vol: {pred_vol * 100:.2f}% | Current IV: {iv_daily[-1] * 100:.2f}%")
print(f"Vol edge: {edge * 100:+.2f}%")

