# -*- coding: utf-8 -*-
"""The Black-Scholes Framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
from typing import Union, Tuple

class BlackScholes:
    def __init__(self, S: float, K: float, T: float, r: float, sigma: float, q: float = 0.0):
        self.S = S
        self.K = K
        self.T = T  # time to expiry in years
        self.r = r
        self.q = q
        self.sigma = sigma
        self._compute_d1_d2()

    def _compute_d1_d2(self):
        """Compute d1 and d2 from BS formula."""
        sqrt_T = np.sqrt(self.T)
        self.d1 = (np.log(self.S / self.K) + (self.r - self.q + 0.5 * self.sigma ** 2) * self.T) / (self.sigma * sqrt_T)
        self.d2 = self.d1 - self.sigma * sqrt_T
        # Store CDF/PDF values
        self.Nd1 = norm.cdf(self.d1)
        self.Nd2 = norm.cdf(self.d2)
        self.Nnd1 = norm.cdf(-self.d1)
        self.Nnd2 = norm.cdf(-self.d2)
        self.nd1 = norm.pdf(self.d1)  # phi(d1)
        self.disc_r = np.exp(-self.r * self.T)
        self.disc_q = np.exp(-self.q * self.T)

    def call_price(self) -> float:
        return self.S * self.disc_q * self.Nd1 - self.K * self.disc_r * self.Nd2

    def put_price(self) -> float:
        return self.K * self.disc_r * self.Nnd2 - self.S * self.disc_q * self.Nnd1

    def delta(self, option_type: str = 'call') -> float:
        """Delta: dC/dS or dP/dS"""
        if option_type.lower() == 'call':
            return self.disc_q * self.Nd1
        else:  # put
            return -self.disc_q * self.Nnd1

    def vega(self) -> float:
        """Vega (per 1% move in sigma, i.e., divided by 100)"""
        raw_vega = self.S * self.disc_q * self.nd1 * np.sqrt(self.T)
        return raw_vega / 100.0  # standard market convention: per 1 vol point

    def theta(self, option_type: str = 'call') -> float:
        """Theta (per calendar day)"""
        common = -(self.S * self.disc_q * self.nd1 * self.sigma) / (2 * np.sqrt(self.T))
        if option_type.lower() == 'call':
            rate_term = -self.r * self.K * self.disc_r * self.Nd2 + self.q * self.S * self.disc_q * self.Nd1
        else:
            rate_term = self.r * self.K * self.disc_r * self.Nnd2 - self.q * self.S * self.disc_q * self.Nnd1
        return (common + rate_term) / 365.0  # per calendar day

    def rho(self, option_type: str = 'call') -> float:
        """Rho (per 1% move in r)"""
        if option_type.lower() == 'call':
            return self.K * self.T * self.disc_r * self.Nd2 / 100.0
        else:
            return -self.K * self.T * self.disc_r * self.Nnd2 / 100.0

    def gamma(self) -> float:
        """Gamma: d^2C/dS^2 (same for call and put)"""
        return (self.disc_q * self.nd1) / (self.S * self.sigma * np.sqrt(self.T))

    def vanna(self) -> float:
        """Vanna: d^2C/(dS dsigma) = dDelta / dsigma """
        return -self.disc_q * self.nd1 * self.d2 / self.sigma

    def volga(self) -> float:
        """Volga (Vomma): d^2C/dsigma^2 = dVega / dsigma"""
        raw_vega = self.S * self.disc_q * self.nd1 * np.sqrt(self.T)
        return raw_vega * self.d1 * self.d2 / self.sigma

    def summary(self, option_type: str = 'call') -> dict:
        """Return a dictionary of all prices and greeks."""
        price_fn = self.call_price if option_type == 'call' else self.put_price
        return {
            'price': price_fn(),
            'delta': self.delta(option_type),
            'gamma': self.gamma(),
            'theta': self.theta(option_type),
            'vega': self.vega(),
            'rho': self.rho(option_type),
            'vanna': self.vanna(),
            'volga': self.volga(),
            'd1': self.d1,
            'd2': self.d2,
        }

    def prob_itm_rn(self) -> float:
        """Risk-neutral probability of finishing ITM (for call = Phi(d2))."""
        return self.Nd2

if __name__ == '__main__':
    # ATM call: S=100, K=100, T=1yr, r=5%, q=0%, sigma=20%
    bs = BlackScholes(S=100, K=100, T=1.0, r=0.05, sigma=0.20, q=0.0)
    results = bs.summary('call')

    print("=" * 50)
    print(" BLACK-SCHOLES ATM CALL SUMMARY ")
    print("=" * 50)
    for key, val in results.items():
        print(f" {key:>8s}: {val:12.6f}")

    print(f"\n RN prob ITM (Phi(d2)): {bs.prob_itm_rn():.6f}")

    S_range = np.linspace(60, 140, 500)
    prices, deltas, gammas, vegas, thetas = [], [], [], [], []

    for S in S_range:
        b = BlackScholes(S=S, K=100, T=1.0, r=0.05, sigma=0.20)
        prices.append(b.call_price())
        deltas.append(b.delta('call'))
        gammas.append(b.gamma())
        vegas.append(b.vega())
        thetas.append(b.theta('call'))

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('Black-Scholes Call Option: Price and Greeks vs Spot', fontsize=14, fontweight='bold')

    # Price
    axes[0, 0].plot(S_range, prices, 'b-', linewidth=2)
    axes[0, 0].axvline(x=100, color='gray', linestyle='--', alpha=0.5)
    axes[0, 0].set_title('Call Price')
    axes[0, 0].set_xlabel('S')
    axes[0, 0].fill_between(S_range, np.maximum(S_range - 100, 0), prices, alpha=0.2, color='blue', label='Time Value')
    axes[0, 0].plot(S_range, np.maximum(S_range - 100, 0), 'r--', label='Intrinsic')
    axes[0, 0].legend()

    # Delta
    axes[0, 1].plot(S_range, deltas, 'g-', linewidth=2)
    axes[0, 1].axvline(x=100, color='gray', linestyle='--', alpha=0.5)
    axes[0, 1].axhline(y=0.5, color='gray', linestyle=':', alpha=0.5)
    axes[0, 1].set_title('Delta')
    axes[0, 1].set_xlabel('S')

    # Gamma
    axes[1, 0].plot(S_range, gammas, 'm-', linewidth=2)
    axes[1, 0].axvline(x=100, color='gray', linestyle='--', alpha=0.5)
    axes[1, 0].set_title('Gamma')
    axes[1, 0].set_xlabel('S')

    # Vega
    axes[1, 1].plot(S_range, [v * 100 for v in vegas], 'r-', linewidth=2)
    axes[1, 1].axvline(x=100, color='gray', linestyle='--', alpha=0.5)
    axes[1, 1].set_title('Vega (per vol point)')
    axes[1, 1].set_xlabel('S')

    plt.tight_layout()
    plt.savefig('bs_greeks.png', dpi=150, bbox_inches='tight')
    plt.show()

