# -*- coding: utf-8 -*-
"""Implied Volatility Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
from scipy.optimize import brentq
from typing import Optional

# ==========================================
# BS pricing helper
# ==========================================
def bs_price(S: float, K: float, T: float, r: float, sigma: float, q: float = 0.0, option_type: str = 'call') -> float:
    """Black-Scholes price for call or put."""
    if T <= 0:
        # At expiry
        if option_type == 'call':
            return max(S * np.exp(-q * T) - K * np.exp(-r * T), 0.0)
        else:
            return max(K * np.exp(-r * T) - S * np.exp(-q * T), 0.0)

    sqrt_T = np.sqrt(T)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * sqrt_T)
    d2 = d1 - sigma * sqrt_T
    disc_r = np.exp(-r * T)
    disc_q = np.exp(-q * T)

    if option_type.lower() == 'call':
        return S * disc_q * norm.cdf(d1) - K * disc_r * norm.cdf(d2)
    else:
        return K * disc_r * norm.cdf(-d2) - S * disc_q * norm.cdf(-d1)

def bs_vega(S: float, K: float, T: float, r: float, sigma: float, q: float = 0.0) -> float:
    """Black-Scholes vega (raw, not per 1%)."""
    if T <= 0 or sigma <= 0:
        return 0.0
    sqrt_T = np.sqrt(T)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * sqrt_T)
    return S * np.exp(-q * T) * norm.pdf(d1) * sqrt_T

# ==========================================
# Newton-Raphson IV Solver
# ==========================================
def iv_newton(market_price: float, S: float, K: float, T: float, r: float, q: float = 0.0, option_type: str = 'call', tol: float = 1e-8, max_iter: int = 100, sigma0: Optional[float] = None) -> Optional[float]:
    """
    Compute IV via Newton-Raphson.
    Returns None if convergence fails.
    """
    if T <= 0:
        return None

    # Initial guess: Brenner-Subrahmanyam for ATM
    if sigma0 is None:
        F = S * np.exp((r - q) * T)  # forward price
        if option_type == 'call':
            sigma = market_price / (S * np.exp(-q * T) * np.sqrt(T / (2 * np.pi)))
        else:
            sigma = market_price / (K * np.exp(-r * T) * np.sqrt(T / (2 * np.pi)))
        sigma = max(sigma, 1e-4)  # Ensure positive start
    else:
        sigma = sigma0

    for i in range(max_iter):
        price = bs_price(S, K, T, r, sigma, q, option_type)
        vega = bs_vega(S, K, T, r, sigma, q)

        error = price - market_price
        if abs(error) < tol:
            return sigma

        # Guard against near-zero vega (deep ITM/OTM)
        if abs(vega) < 1e-12:
            break  # Fall back to Brent

        sigma -= error / vega
        sigma = max(sigma, 1e-8)  # Keep positive

    return None  # Newton failed, caller should use Brent

# ==========================================
# Brent's Method IV Solver (Robust)
# ==========================================
def iv_brent(market_price: float, S: float, K: float, T: float, r: float, q: float = 0.0, option_type: str = 'call', sigma_lo: float = 1e-6, sigma_hi: float = 20.0, tol: float = 1e-8) -> Optional[float]:
    """
    Compute IV via Brent's method.
    Guaranteed to find the root in [sigma_lo, sigma_hi].
    """
    obj = lambda s: bs_price(S, K, T, r, s, q, option_type) - market_price

    f_lo = obj(sigma_lo)
    f_hi = obj(sigma_hi)

    # Check bounds: root must be bracketed
    if f_lo * f_hi > 0:
        # Expand search range
        if f_lo > 0:
            return None  # Market price below intrinsic
        sigma_hi = 50.0
        f_hi = obj(sigma_hi)
        if f_lo * f_hi > 0:
            return None

    try:
        iv = brentq(obj, sigma_lo, sigma_hi, xtol=tol, rtol=tol)
        return iv
    except ValueError:
        return None

# ==========================================
# Combined IV Solver: Newton first, Brent as fallback
# ==========================================
def implied_vol(market_price: float, S: float, K: float, T: float, r: float, q: float = 0.0, option_type: str = 'call', tol: float = 1e-7) -> Optional[float]:
    """
    Production-quality IV solver.
    Strategy: Try Newton-Raphson (fast), fall back to Brent (robust).
    """
    # Validate no-arbitrage bounds
    disc_r = np.exp(-r * T)
    disc_q = np.exp(-q * T)

    if option_type == 'call':
        lower_bound = max(S * disc_q - K * disc_r, 0.0)
        upper_bound = S * disc_q
    else:
        lower_bound = max(K * disc_r - S * disc_q, 0.0)
        upper_bound = K * disc_r

    if market_price <= lower_bound:
        print(f"Warning: Price {market_price:.4f} <= lower bound {lower_bound:.4f}. Market price violates no-arb.")
        return None

    if market_price >= upper_bound * (1 - 1e-8):
        print(f"Warning: Price {market_price:.4f} >= upper bound {upper_bound:.4f}.")
        return None

    # Try Newton-Raphson first
    iv = iv_newton(market_price, S, K, T, r, q, option_type, tol)

    # Fall back to Brent if Newton fails
    if iv is None or iv < 1e-6 or iv > 20.0:
        iv = iv_brent(market_price, S, K, T, r, q, option_type, tol=tol)

    return iv

# ==========================================
# EXAMPLE: Reconstruct a smile from market prices
# ==========================================
def extract_smile_from_prices(S: float, T: float, r: float, q: float, strikes: np.ndarray, market_prices: np.ndarray, option_types: list) -> np.ndarray:
    """Extract full IV smile from market option prices."""
    ivs = []
    for K, price, opt_type in zip(strikes, market_prices, option_types):
        iv = implied_vol(price, S, K, T, r, q, opt_type)
        ivs.append(iv if iv is not None else np.nan)
    return np.array(ivs)

# ==========================================
# DEMO
# ==========================================
if __name__ == '__main__':
    S, r, q, T = 100.0, 0.05, 0.0, 1.0

    # Generate "market" prices with a known vol smile
    strikes = np.array([70, 80, 85, 90, 95, 100, 105, 110, 115, 120, 130])
    true_ivs = np.array([0.35, 0.30, 0.27, 0.25, 0.23, 0.22, 0.23, 0.25, 0.27, 0.29, 0.33])
    opt_types = ['put' if K < S else 'call' for K in strikes]

    # Generate market prices
    mkt_prices = np.array([
        bs_price(S, K, T, r, iv, q, ot)
        for K, iv, ot in zip(strikes, true_ivs, opt_types)
    ])

    # Add small noise to simulate market
    np.random.seed(42)
    mkt_prices += np.random.normal(0, 0.01, len(mkt_prices))
    mkt_prices = np.maximum(mkt_prices, 1e-4)

    # Extract IV smile
    extracted_ivs = extract_smile_from_prices(S, T, r, q, strikes, mkt_prices, opt_types)

    print("\nIV Extraction Results:")
    print(f"{'Strike':>8} {'Type':>6} {'Mkt Price':>12} {'True IV':>10} {'Extracted IV':>14} {'Error (bp)':>12}")
    print("-" * 70)
    for K, ot, mp, tiv, eiv in zip(strikes, opt_types, mkt_prices, true_ivs, extracted_ivs):
        err_bp = abs(tiv - eiv) * 10000 if eiv is not None else np.nan
        eiv_str = f"{eiv:.6f}" if eiv is not None else "FAILED"
        print(f"{K:>8.0f} {ot:>6} {mp:>12.4f} {tiv:>10.4f} {eiv_str:>14} {err_bp:>10.2f}")

