# -*- coding: utf-8 -*-
"""Volatility Risk Premium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

def compute_vrp_analysis(iv_series: pd.Series, rv_series: pd.Series, lag: int = 21) -> pd.DataFrame:
  df = pd.DataFrame({'IV': iv_series, 'RV_fwd': rv_series})
  df = df.dropna()

  df['VRP'] = df['IV'] - df['RV_fwd']

  stats = {
      "Mean IV": df['IV'].mean(),
      "Mean RV": df['RV_fwd'].mean(),
      "Mean VRP": df['VRP'].mean(),
      "Std VRP": df['VRP'].std(),
      "VRP > 0(frac)": (df['VRP'] > 0).mean(),
      "Sharpe of VRP": df['VRP'].mean() / df['VRP'].std(),}

  from numpy.polynomial import polynomial as p

  beta, alpha = np.polyfit(df['IV'], df['RV_fwd'], 1)
  r_squared = pearsonr(df['IV'], df['RV_fwd'])[0]**2

  stats.update({
      'Regrssion alpha': alpha,
      'Regression beta': beta,
      'R squared': r_squared,
  })

  return pd.Series(stats)

np.random.seed(12)
n = 250
true_vol = 0.15 + 0.1 * np.random.beta(2, 5, n)
vrp = 0.03 + 0.01 * np.random.randn(n)

iv_sim = true_vol + vrp
rv_sim = true_vol + 0.02 * np.random.randn(n)

results = compute_vrp_analysis(pd.Series(iv_sim), pd.Series(rv_sim))

print("\nVRP Analysis Results (synthetic Data): ")
for k, v, in results.items():
  print(f"{k:30s}: {v:.4f}")

