# -*- coding: utf-8 -*-
"""Volatility Smile and Skew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt

def svi(k, a, b, rho, m, sigma_s):
  return a + b *(rho * (k - m) + np.sqrt((k - m)**2 + sigma_s**2))

def svi_iv(k, tau, a, b, rho, m, sigma_s):
  w = svi(k, a, b, rho, m, sigma_s)
  w = np.maximum(w, 1e-8)
  return np.sqrt(w / tau)

def svi_no_arbitrage_check(params, k_range=None):
  a, b, rho, m, sigma_s = params
  if k_range is None:
    k_range = np.linspace(-2, 2, 200)

  w = svi(k_range, a, b, rho, m, sigma_s)

  if np.any(w <= 0):
     return False

  dw = np.gradient(w, k_range)
  d2w = np.gradient(dw, k_range)
  g = (1 - k_range * dw / (2 * w ) ) **2 - dw **2 / 4 * (1/ w + 0.25) + d2w / 2
  return np.all(g >= -1e-8)

def fit_svi (k_obs: np.ndarray, w_obs:np.ndarray, tau: float) -> np.ndarray:
  a0 = np.mean(w_obs) * 0.5
  b0 = 0.1
  rho0 = -0.5
  m0 = 0.0
  s0 = 0.1
  x0 = [a0, b0, rho0, m0, s0]

  bounds = [(0 , None), (1e-4 , None ), (-0.999 , 0.999), (None , None) , (1e-4, None),]

  def objective (params):
    a , b , rho , m , sigma_s = params
    w_fit = svi(k_obs , a, b, rho, m, sigma_s)
    return np.sum((w_fit - w_obs) **2)
  result = minimize(objective, x0, method='L-BFGS-B', bounds=bounds , options ={'ftol': 1e-12 , 'gtol': 1e-8})
  return result.x

if __name__ == '__main__':
  tau = 1/12
  k_obs = np. array ([ -0.3 , -0.2 , -0.15 , -0.1 , -0.05 , 0.0 , 0.05 , 0.1 , 0.15 , 0.2 , 0.3])
  iv_obs = np. array ([0.38 , 0.31 , 0.28 , 0.26 , 0.24 , 0.22 , 0.22 , 0.23 , 0.24 , 0.25 , 0.27])
  w_obs = iv_obs **2 * tau
  params = fit_svi (k_obs, w_obs, tau)
  a , b , rho , m , sigma_s = params
  print (f" Fitted SVI params : a={a:.4f} , b={b:.4f} , "f"rho ={ rho :.4f} , m={m:.4f} , sigma_s ={ sigma_s :.4f}")
  print (f"No - arbitrage check : {svi_no_arbitrage_check(params)}")
  k_fine = np.linspace(-0.5, 0.5, 300)
  iv_fit = svi_iv(k_fine, tau, *params)

  plt.figure(figsize=(10 , 6))
  plt.plot(k_obs, iv_obs * 100 , 'ko', markersize=8 , label='Market Quotes')
  plt.plot(k_fine, iv_fit * 100 , 'b-', linewidth=2 , label ='SVI Fit')
  plt.xlabel('Log - moneyness $k = \\ ln(K/F)$', fontsize =12)
  plt.ylabel('Implied Volatility (\\%)', fontsize =12)
  plt.title('SVI Smile Fit (1 - Month Expiry )', fontsize =14)
  plt.legend(fontsize =11)
  plt.grid(True , alpha =0.4)
  plt.savefig('svi_fit .png', dpi =150 , bbox_inches ='tight')
  plt.show()

