# -*- coding: utf-8 -*-
"""The Volatility Smile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
from scipy.optimize import brentq

def bs_call(S, K, T, r, q, sigma):
  d1 = (np.log(S/K) + (r - q + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
  d2 = d1 - sigma*np.sqrt(T)
  return S*np.exp(-q*T)*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)

def bs_vega(S, K, T, r, q, sigma):
  d1 = (np.log(S/K) + (r - q + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
  return S*np.exp(-q*T)*norm.pdf(d1)*np.sqrt(T)

def implied_vol_newton(C_mkt, S, K, T, r, q, tol=1e-8, max_iter=100):
  if T <= 0:
    return np.nan
  intrinsic = max(S*np.exp(-q*T) - K*np.exp(-r*T), 0.0)
  if C_mkt <= intrinsic + 1e-10:
    return np.nan

  F = S * np.exp((r - q)*T)
  m = F - K if K <= F else K - F
  sigma = (np.sqrt(2*np.pi/T) * (C_mkt - max(S*np.exp(-q*T) - K*np.exp(-r*T), 0)) / (S*np.exp(-q*T)))
  sigma = max(sigma, 0.001)

  for _ in range(max_iter):
    price = bs_call(S, K, T, r, q, sigma)
    vega = bs_vega(S, K, T, r, q, sigma)
    if abs(vega) < 1e-12:
      break
    diff = price - C_mkt
    if abs(diff) < tol:
      return sigma
    sigma -= diff / vega
    sigma = max(sigma, 1e-6)

  try:
    return brentq(lambda s: bs_call(S, K, T, r, q, s) - C_mkt, 1e-4, 5.0, xtol=1e-8)

  except ValueError:
      return np.nan

def compute_smile(S, T, r, q, strikes, prices, option_type='call'):
  ivs = []
  for K, C in zip(strikes, prices):
    if option_type == 'put':
      C = C + S*np.exp(-q*T) - K*np.exp(-r*T)
    ivs.append(implied_vol_newton(C, S, K, T, r, q))
    return np.array(ivs)

if __name__ == '__main__':
  S, T, r, q = 4500, 0.083, 0.05, 0.015
  F = S * np.exp((r-q)*T)
  strikes = np.arange(3800, 5200, 50)
  true_ivs = 0.22 - 0.5*np.log(strikes/F) + 0.8*np.log(strikes/F)**2
  prices = [bs_call(S, K, T, r, q, iv) for K, iv in zip(strikes, true_ivs)]
  recovered_ivs = compute_smile(S, T, r, q, strikes, prices)
  max_error = np.nanmax(np.abs(recovered_ivs - true_ivs))
  print(f"Max IV recovery error: {max_error:.2e}")

