# -*- coding: utf-8 -*-
"""The Volatility Surface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.optimize import minimize, differential_evolution
import warnings

def svi_raw(k, a, b, rho, m, sigma):
  return a + b * (rho * (k - m) + np.sqrt((k - m)**2 + sigma**2))

def svi_no_arb_penalty(params):
  a, b, rho, m, sigma = params
  p1 = max(0, b*(1+abs(rho)) - 4)**2
  p2 = max(0, b*sigma*np.sqrt(1-rho**2) - 4)**2
  k_min = m - sigma * np.abs(rho) / np.sqrt(1 - rho**2) if abs(rho) < 1 else m
  w_min = svi_raw(k_min, a, b, rho, m, sigma)
  p3 = max(0, -w_min)**2 * 1e6
  return 1e4 * (p1 + p2 + p3)

def svi_g_function(k, a, b, rho, m, sigma):
  w = svi_raw(k, a, b, rho, m, sigma)
  d = k - m
  sq = np.sqrt(d**2 + sigma**2)
  wprime = b * (rho + d / sq)
  wprime2 = b * sigma**2 / sq**3
  term1 = (1 - k*wprime / (2*w))**2
  term2 = wprime**2 / 4 * (1/w + 1/4)
  term3 = wprime2 / 2
  return term1 - term2 + term3

def fit_svi_slice(k_market, iv_market, T):
  w_market = iv_market**2 * T

  def objective(params):
    a, b, rho, m, sigma = params
    w_fit = svi_raw(k_market, a, b, rho, m, sigma)
    if np.any(w_fit <= 0):
      return 1e9
    fit_err = np.sum((np.sqrt(w_fit) - iv_market)**2)
    arb_pen = svi_no_arb_penalty(params)
    return fit_err + arb_pen

  bounds = [(-0.5, 0.5), (0.001, 2.0), (-0.99, 0.99), (-0.5, 0.5), (0.001, 1.0)]
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    result = differential_evolution(objective, bounds, seed=12, maxiter=1000, tol=1e-10, polish=True)

  params_opt = result.x
  k_check = np.linspace(k_market.min()-0.1, k_market.max()+0.1, 500)
  g_vals = svi_g_function(k_check, *params_opt)
  if np.any(g_vals < -1e-6):
    print(f" WARNING: Butterfly violation! min g = {g_vals.min():.4e}")

  return params_opt, result.fun

if __name__ == '__main__':
  T = 1/12
  F = 4500.0
  k_mkt = np.array([-0.20, -0.15, -0.10, -0.05, 0.0, 0.05, 0.10])
  iv_mkt = np.array([0.335, 0.290, 0.253, 0.224, 0.205, 0.195, 0.192])
  params, obj = fit_svi_slice(k_mkt, iv_mkt, T)
  a, b, rho, m, sigma = params
  print(f"SVI params: a={a:.4f}, b={b:.4f}, rho={rho:.4f}, "
  f"m={m:.4f}, sigma={sigma:.4f}")
  print(f"Objective: {obj:.6f}")
  k_fine = np.linspace(-0.25, 0.15, 200)
  iv_fine = np.sqrt(np.maximum(svi_raw(k_fine, a, b, rho, m, sigma), 1e-9) / T)
  print(f"ATM vol (k=0): {np.sqrt(svi_raw(0.0, a, b, rho, m, sigma)/T)*100:.2f}%")

