# -*- coding: utf-8 -*-
"""The term structure of Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.integrate import quad

def var_swap_strike(smile_func, F, T, r, K_min=None, K_max=None):
  from scipy.stats import norm

  def bs_call_local(K, iv):
    d1 = (np.log(F/K) + 0.5*iv**2*T) / (iv*np.sqrt(T))
    d2 = d1 - iv*np.sqrt(T)
    return np.exp(-r*T) * (F*norm.cdf(d1) - K*norm.cdf(d2))

  def bs_put_local(K, iv):
    d1 = (np.log(F/K) + 0.5*iv**2*T) / (iv*np.sqrt(T))
    d2 = d1 - iv*np.sqrt(T)
    return np.exp(-r*T) * (K*norm.cdf(-d2) - F*norm.cdf(-d1))

  if K_min is None:
    K_min = F * np.exp(-5 * smile_func(F) * np.sqrt(T))

  if K_max is None:
    K_max = F * np.exp(+5 * smile_func(F) * np.sqrt(T))

  def put_integrand(K):
    iv = smile_func(K)
    if iv <= 0 or np.isnan(iv):
      return 0.0
    return 2.0 / T * bs_put_local(K, iv) / K**2

  def call_integrand(K):
    iv = smile_func(K)
    if iv <= 0 or np.isnan(iv):
      return 0.0

    return 2.0 / T * bs_call_local(K, iv) / K**2

  put_contrib, _ = quad(put_integrand, K_min, F, limit=200)
  call_contrib, _ = quad(call_integrand, F, K_max, limit=200)
  K_var = put_contrib + call_contrib
  return K_var

if __name__ =='__main__':
  from scipy.interpolate import CubicSpline
  F, T, r = 4500, 0.25, 0.05
  k_nodes = np.array([-0.20, -0.10, 0.0, 0.10, 0.20])
  iv_nodes = np.array([0.280, 0.232, 0.200, 0.186, 0.182])
  K_nodes = F * np.exp(k_nodes)
  cs = CubicSpline(K_nodes, iv_nodes, extrapolate=True)
  smile_f = lambda K: float(cs(K))

  Kvar = var_swap_strike(smile_f, F, T, r)
  atm_iv = smile_f(F)

  print(f"ATM variance: {atm_iv**2*100:.4f}% ann.")
  print(f"Var swap strike: {Kvar*100:.4f}% ann.")
  print(f"Convexity adj: {(Kvar - atm_iv**2)*100:.4f}% ann.")
  print(f"ATM vol: {atm_iv*100:.2f}%")
  print(f"Var swap vol: {np.sqrt(Kvar)*100:.2f}%")

