# -*- coding: utf-8 -*-
"""Gamma Scalping Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

def bs_price(S, K, T, r, sigma, option_type='call'):
  if T <= 0:
    return max(0, S - K) if option_type == 'call' else max(0, K - S)

  d1 = (np.log(S/K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
  d2 = d1 - sigma * np.sqrt(T)

  if option_type == 'call':
    return S*norm.cdf(d1) - K * np.exp(-r*T)*norm.cdf(d2)
  else:
    return K * np.exp(-r*T)*norm.cdf(-d2) - S*norm.cdf(-d1)

def bs_delta(S, K, T, r, sigma, option_type='call'):
  if T <= 0:
    return 1.0 if (option_type == 'call' and S > K) else 0.0

  d1 = (np.log(S/K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
  d2 = d1 - sigma * np.sqrt(T)

  if option_type == 'call':
    return norm.cdf(d1)
  else:
    return norm.cdf(d1) - 1.0

def bs_gamma(S, K, T, r, sigma, option_type='call'):
  if T <= 0:
    return 0.0

  d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
  return norm.pdf(d1) / (S * sigma * np.sqrt(T))

def bs_theta(S, K , T, r, sigma, option_type='call'):
  if T <= 0:
    return 0.0

  d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
  d2 = d1 - sigma * np.sqrt(T)

  theta = -(S*norm.pdf(d1)*sigma) / (2*np.sqrt(T))

  if option_type == 'call':
    theta -= (r*K*np.exp(-r*T)*norm.cdf(d2))
  else:
    theta += (r*K*np.exp(-r*T)*norm.cdf(-d2))
  return theta / 252

def gamma_scalping_simulation(S0=100.0, K=100.0, T_days=21, r=0.05, sigma_iv=0.20, sigma_rv=None,
                              rebalance_freq=1, n_paths=5000, seed=12):
  np.random.seed(seed)
  T = T_days / 252
  dt = 1/252
  N = T_days

  if sigma_rv is None:
    sigma_rv = sigma_iv

  V0_call = bs_price(S0, K, T, r, sigma_iv, 'call')
  V0_put = bs_price(S0, K, T, r, sigma_iv, 'put')
  V0 = V0_call + V0_put

  pnl_paths = []
  gamma_pnl_paths = []
  theta_pnl_paths = []

  for _ in range(n_paths):
    S = S0
    t = 0.0

    d_call = bs_delta(S, K, T, r, sigma_iv, 'call')
    d_put = bs_delta(S, K, T, r, sigma_iv, 'put')
    delta = d_call + d_put

    hedge_shares = -delta
    cash = delta * S - V0

    cumulative_gamma_pnl = 0.0
    cumulative_theta_pnl = 0.0

    for step in range(N):
      tau = (N - step) / 252

      Z = np.random.randn()
      dS = S * (r * dt + sigma_rv * np.sqrt(dt) * Z)
      S_new = S + dS

      gamma = bs_gamma(S, K, tau, r, sigma_iv)
      theta = bs_theta(S, K, tau, r, sigma_iv, 'call') + bs_theta(S, K, tau, r, sigma_iv, 'put')

      gamma_pnl = 0.5 * gamma * dS**2
      theta_pnl = theta

      cumulative_gamma_pnl += gamma_pnl
      cumulative_theta_pnl += theta_pnl

      S = S_new

      if step % rebalance_freq == 0:
        tau_new = (N - step - rebalance_freq) / 252
        d_call_new = bs_delta(S, K, max(tau_new, 1e-6), r, sigma_iv, 'call')
        d_put_new = bs_delta(S, K, max(tau_new, 1e-6), r, sigma_iv, 'put')
        delta_new = d_call_new + d_put_new
        delta_change = delta_new - delta
        cash -= delta_change * S

        hedge_shares = -delta_new
        delta = delta_new

    payoff = abs(S - K)
    terminal_pnl = payoff - V0 + cumulative_gamma_pnl + cumulative_theta_pnl
    pnl_paths.append(terminal_pnl)
    gamma_pnl_paths.append(cumulative_gamma_pnl)
    theta_pnl_paths.append(cumulative_theta_pnl)

  return {'pnl': np.array(pnl_paths),
          'gamma_pnl': np.array(gamma_pnl_paths),
          'theta_pnl': np.array(theta_pnl_paths),
          'V0': V0,
          'mean_pnl': np.mean(pnl_paths),
          'std_pnl': np.std(pnl_paths),
          'sharpe': np.mean(pnl_paths) / np.std(pnl_paths) if np.std(pnl_paths) > 0 else 0}

scenarios = {'RV = IV (fair)': {'sigma_rv': 0.20, 'sigma_iv': 0.20},
             'RV > IV (fair)': {'sigma_rv': 0.25, 'sigma_iv': 0.20},
             'RV < IV (fair)': {'sigma_rv': 0.15, 'sigma_iv': 0.20}}

for name, params in scenarios.items():
  result = gamma_scalping_simulation(**params)
  print(f"\n{'='*50}")
  print(f"Scenario: {name}")
  print(f" Mean PnL: ${result['mean_pnl']:.4f}")
  print(f" Std PnL: ${result['std_pnl']:.4f}")
  print(f" Sharpe Ratio: {result['sharpe']:.3f}")
  print(f" Gamma PnL: ${result['gamma_pnl'].mean():.4f}")
  print(f" Theta PnL: ${result['theta_pnl'].mean():.4f}")

