# -*- coding: utf-8 -*-
"""Measuring VRP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import pandas as pd
import numpy as np
import yfinance as yf

def compute_historical_vrp(ticker='^GSPC', vix_ticker='^VIX', start='2010-01-01', window=21):
  spy = yf.download(ticker, start=start)['Adj Close']
  vix = yf.download(vix_ticker, start=start)['Adj Close']
  log_ret = np.log(spy / spy.shift(1).dropna())

  rv_daily = log_ret.rolling(window).std() * np.sqrt(252)

  vix_lagged = vix.shift(window) / 100

  combined = pd.DataFrame({'VIX': vix / 100,
                           'VIX_lagged': vix_lagged,
                           'RV': rv_daily,
                           'VRP': vix_lagged - rv_daily}).dropna()

  print(f"\n=== VRP Statistics(S&P 500) ===")
  print(f"Mean VRP: {combined['VRP'].mean()*100:.2f}%")
  print(f"Median VRP: {combined['VRP'].median()*100:.2f}")
  print(f"% VRP > 0: {(combined['VRP'] > 0).mean()*100:.1f}%")
  print(f"Std(VRP): {combined['VRP'].std()*100:.2f}% ")
  print(f"Skewness: {combined['VIX'].skew():.2f}")
  print(f"Mean VIX: {combined['VRP'].mean()*100:.2f}%")
  print(f"Mean RV: {combined['RV'].mean()*100:.2f}%")

  return combined

def variance_risk_premium(log_returns, iv_series, window=21):
  rv_sq = log_returns.rolling(window).var() * 252
  iv_seq = (iv_series / 100) ** 2
  iv_seq_lagged = iv_seq.shift(window)
  vrp_var = iv_seq_lagged - rv_sq
  return vrp_var

