# -*- coding: utf-8 -*-
"""Volatility Trading Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.optimize import brentq
from dataclasses import dataclass
from typing import Literal, Optional
import warnings


@dataclass
class BSGreeks:
    price: float
    delta: float
    gamma: float
    theta: float
    vega: float
    rho: float
    vanna: float
    volga: float
    charm: float
    speed: float

def black_scholes_full(
    S: float, K: float, T: float, r: float, sigma: float,
    option_type: Literal['call', 'put'] = 'call'
) -> BSGreeks:
    if T <= 1e-8:
        intrinsic = max(S - K, 0) if option_type == 'call' else max(K - S, 0)
        return BSGreeks(
            intrinsic,
            1.0 if option_type == 'call' and S > K else 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
        )

    sqrt_T = np.sqrt(T)
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * sqrt_T)
    d2 = d1 - sigma * sqrt_T
    n_d1 = norm.pdf(d1)
    N_d1 = norm.cdf(d1)
    N_d2 = norm.cdf(d2)
    Nm_d1 = norm.cdf(-d1)
    Nm_d2 = norm.cdf(-d2)
    disc = np.exp(-r * T)

    if option_type == 'call':
        price = S * N_d1 - K * disc * N_d2
        delta = N_d1
        rho_v = K * T * disc * N_d2 / 100
        theta = (-(S * n_d1 * sigma / (2 * sqrt_T)) - r * K * disc * N_d2) / 252
    else:
        price = K * disc * Nm_d2 - S * Nm_d1
        delta = N_d1 - 1
        rho_v = -K * T * disc * Nm_d2 / 100
        theta = (-(S * n_d1 * sigma / (2 * sqrt_T)) + r * K * disc * Nm_d2) / 252

    gamma = n_d1 / (S * sigma * sqrt_T)
    vega = S * sqrt_T * n_d1 / 100

    vanna = -n_d1 * d2 / sigma

    volga = vega * d1 * d2 / sigma * 100

    if option_type == 'call':
        charm = -n_d1 * (2 * r * T - d2 * sigma * sqrt_T) / (2 * T * sigma * sqrt_T) / 252
    else:
        charm = -n_d1 * (2 * r * T - d2 * sigma * sqrt_T) / (2 * T * sigma * sqrt_T) / 252

    speed = -gamma * (1 + d1 / (sigma * sqrt_T)) / S

    return BSGreeks(price, delta, gamma, theta, vega, rho_v, vanna, volga, charm, speed)

def implied_vol(
    market_price: float, S: float, K: float, T: float, r: float,
    option_type: Literal['call', 'put'] = 'call',
    tol: float = 1e-7
) -> Optional[float]:
    intrinsic = max(S - K, 0) if option_type == 'call' else max(K - S, 0)
    if market_price <= intrinsic + tol:
        return None

    def objective(sigma):
        g = black_scholes_full(S, K, T, r, sigma, option_type)
        return g.price - market_price

    try:
        iv = brentq(objective, 1e-4, 10.0, xtol=tol, maxiter=200)
        return iv
    except (ValueError, RuntimeError):
        return None

class OptionPnLDecomposer:
    def __init__(self, S0, K, T, r, sigma_iv, option_type='call'):
        self.S0 = S0
        self.K = K
        self.T = T
        self.r = r
        self.sigma_iv = sigma_iv
        self.option_type = option_type
        self.greeks0 = black_scholes_full(S0, K, T, r, sigma_iv, option_type)

    def decompose(self, S1: float, sigma1: float, t_elapsed: float):
        T1 = self.T - t_elapsed
        dS = S1 - self.S0
        dsig = sigma1 - self.sigma_iv

        g0 = self.greeks0
        g1 = black_scholes_full(S1, self.K, T1, self.r, sigma1, self.option_type)

        total_pnl = g1.price - g0.price

        delta_pnl = g0.delta * dS
        gamma_pnl = 0.5 * g0.gamma * dS**2
        theta_pnl = g0.theta * t_elapsed * 252
        vega_pnl = g0.vega * dsig * 100
        vanna_pnl = g0.vanna * dS * dsig
        volga_pnl = 0.5 * g0.volga * dsig**2 / 100

        explained = delta_pnl + gamma_pnl + theta_pnl + vega_pnl + vanna_pnl + volga_pnl
        residual = total_pnl - explained

        return {
            'total_pnl': total_pnl,
            'delta_pnl': delta_pnl,
            'gamma_pnl': gamma_pnl,
            'theta_pnl': theta_pnl,
            'vega_pnl': vega_pnl,
            'vanna_pnl': vanna_pnl,
            'volga_pnl': volga_pnl,
            'explained': explained,
            'residual': residual,
            'greeks1': g1
        }

    def report(self, S1: float, sigma1: float, t_elapsed: float):
        d = self.decompose(S1, sigma1, t_elapsed)
        print(f"\n{'='*55}")
        print(f"{'PnL DECOMPOSITION REPORT':^55}")
        print(f"{'='*55}")
        print(f" Spot : {self.S0:.2f} -> {S1:.2f} (dS={S1 - self.S0:+.2f}, {(S1/self.S0 - 1)*100:+.2f}%)")
        print(f" Vol: {self.sigma_iv*100:.1f}% -> {sigma1*100:.1f}% (d̃={(sigma1 - self.sigma_iv)*100:+.1f}%)")
        print(f" Time : {t_elapsed*252:.1f} days elapsed")
        print(f"{' '*55}")
        print(f" {'Delta PnL':30s}: ${d['delta_pnl']: >8.4f}")
        print(f" {'Gamma PnL':30s}: ${d['gamma_pnl']: >8.4f}")
        print(f" {'Theta PnL':30s}: ${d['theta_pnl']: >8.4f}")
        print(f" {'Vega PnL':30s}: ${d['vega_pnl']: >8.4f}")
        print(f" {'Vanna PnL':30s}: ${d['vanna_pnl']: >8.4f}")
        print(f" {'Volga PnL':30s}: ${d['volga_pnl']: >8.4f}")
        print(f"{' '*55}")
        print(f" {'Explained PnL':30s}: ${d['explained']: >8.4f}")
        print(f" {'Residual (higher order)':30s}: ${d['residual']: >8.4f}")
        print(f"{'='*55}")
        print(f" {'TOTAL PnL':30s}: ${d['total_pnl']: >8.4f}")
        print(f"{'='*55}")
        return d

def simulate_delta_hedge_pnl(
    S0: float = 100, K: float = 100, T_days: float = 21, r: float = 0.05,
    sigma_rv: float = 0.20, sigma_hedge: float = 0.20,
    rebalance_days: int = 1, n_paths: int = 1000, seed: int = 42
) -> pd.DataFrame:
    np.random.seed(seed)
    T = T_days / 252
    dt = rebalance_days / 252
    N = int(T_days // rebalance_days)

    results = []

    for _ in range(n_paths):
        S = S0
        g = black_scholes_full(S, K, T, r, sigma_hedge, 'call')
        V = g.price
        delta = g.delta

        cumulative = {'delta': 0., 'gamma': 0., 'theta': 0., 'vega': 0.}
        stock_path = [S]

        for step in range(N):
            tau = (N - step) * dt
            Z = np.random.randn()
            dS = S * (r * dt + sigma_rv * np.sqrt(dt) * Z)
            S_new = S + dS

            g_new = black_scholes_full(S_new, K, max(tau - dt, 1e-8), r, sigma_hedge, 'call')

            cumulative['delta'] += delta * dS
            cumulative['gamma'] += 0.5 * g.gamma * dS**2
            cumulative['theta'] += g.theta

            S = S_new
            g = g_new
            delta = g.delta
            stock_path.append(S)

        payoff = max(S - K, 0)
        V_final = black_scholes_full(S0, K, T, r, sigma_hedge, 'call').price
        total_pnl = payoff - V_final + sum(cumulative.values())

        theoretical = (0.5 * black_scholes_full(S0, K, T, r, sigma_hedge, 'call').gamma * S0**2 * (sigma_rv**2 - sigma_hedge**2) * T)

        results.append({
            'total_pnl': total_pnl,
            'delta_pnl': cumulative['delta'],
            'gamma_pnl': cumulative['gamma'],
            'theta_pnl': cumulative['theta'],
            'theoretical_pnl': theoretical,
            'final_spot': S,
        })

    return pd.DataFrame(results)

if __name__ == '__main__':
    print("=== Black - Scholes Full Greeks ===")
    g = black_scholes_full(S=100, K=100, T=21/252, r=0.05, sigma=0.20)
    print(f" Price : ${g.price:.4f}")
    print(f" Delta : {g.delta:.4f}")
    print(f" Gamma : {g.gamma:.6f}")
    print(f" Theta : ${g.theta:.4f}/ day")
    print(f" Vega  : ${g.vega:.4f}/1% vol")
    print(f" Vanna : {g.vanna:.6f}")
    print(f" Volga : {g.volga:.6f}")

    print("\n=== PnL Decomposition ===")
    decomp = OptionPnLDecomposer(
        S0=100, K=100, T=21/252, r=0.05,
        sigma_iv=0.20, option_type='call'
    )
    decomp.report(S1=103, sigma1=0.22, t_elapsed=3/252)

    print("\n=== Delta Hedge Simulation ===")
    df = simulate_delta_hedge_pnl(sigma_rv=0.25, sigma_hedge=0.20, n_paths=5000)
    print(f" Mean PnL (simulated): ${df['total_pnl'].mean():.4f}")
    print(f" Mean PnL (theoretical): ${df['theoretical_pnl'].mean():.4f}")
    print(f" Std PnL: ${df['total_pnl'].std():.4f}")

