# -*- coding: utf-8 -*-
"""Delta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

def bs_greeks(S, K, T, r, sigma, q=0.0, option_type='call'):
  if T <= 0:
    raise ValueError('Time to expiry must be positive')

  sqrtT = np.sqrt(T)
  d1 = (np.log(S/K) + (r - q + 0.5 * sigma**2) * T) / (sigma * sqrtT)
  d2 = d1 - sigma*sqrtT

  Nd1 = norm.cdf(d1)
  Nd2 = norm.cdf(d2)
  Nm_d1 = norm.cdf(-d1)
  Nm_d2 = norm.cdf(-d2)
  nd1 = norm.pdf(d1)

  disc_q = np.exp(-q * T)
  disc_r = np.exp(-r * T)

  if option_type == 'call':
    price = S * disc_q * Nd1 - K * disc_r * Nd2
    delta = Nd1 * disc_q
    theta = (-(S * nd1 * sigma * disc_q) / (2 * sqrtT) - r * K * disc_r * Nm_d2 + q * S * disc_q * Nd1) / 365
    rho = K * T * disc_r * Nd2 / 100
  else:
    price = K * disc_r * Nm_d2 - S * disc_q * Nm_d1
    delta = Nm_d1 * -disc_q
    theta = (-(S * nd1 * sigma * disc_q) / (2 * sqrtT) + r * K * disc_r * Nm_d2 - q * S * disc_q * Nm_d1) / 365
    rho = -K * T * disc_r * Nm_d2 / 100

  gamma = disc_q * nd1 / (S * sigma * sqrtT)
  vega = S * sqrtT * nd1 / 100

  return {"price": price, "delta": delta, "theta": theta, "gamma": gamma, "vega": vega, "rho": rho, "d1": d1, "d2": d2}

result = bs_greeks(S=105, K=100, T=0.5, r=0.05 ,sigma=0.25, q=0.02)
print(f"Delta: {result['delta']:.4f}")
print(f"Theta: {result['theta']:.4f}")
print(f"Gamma: {result['gamma']:.4f}")
print(f"Vega: {result['vega']:.4f}")
print(f"Rho: {result['rho']:.4f}")

