# -*- coding: utf-8 -*-
"""Dynamic Greeks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

def simulate_greeks_path(S0, K, T, r, sigma_imp, q=0.0, n_steps=252, n_paths=10000, seed=12):
  np.random.seed(seed)
  dt = T / n_steps
  sqrt_dt = np.sqrt(dt)

  dw = np.random.randn(n_paths, n_steps) * sqrt_dt
  log_returns = (r - q - 0.5 * sigma_imp ** 2) * dt + sigma_imp * dw
  S_paths = S0 + np.exp(np.cumsum(log_returns, axis=1))
  S_paths = np.hstack([np.full((n_paths, 1), S0), S_paths])

  times = np.linspace(0, T, n_steps + 1)
  taus = T - times

  def compute_delta_gamma(S_arr, tau_arr):
    deltas = np.zeros_like(S_arr)
    gammas = np.zeros_like(S_arr)

    for j, tau in enumerate(tau_arr):
      if tau < 1e-6:
        deltas[:, j] = (S_arr[:, j] > K).astype(float)
        gammas[:, j] = 0.0
      else:
        sqrtT = np.sqrt(tau)
        d1 = (np.log(S_arr[:, j] / K) + (r - q + 0.5 * sigma_imp ** 2) * tau) / (sigma_imp * sqrtT)
        deltas[:, j] = np.exp(-q * tau) * norm.cdf(d1)
        gammas[:, j] = np.exp(-q * tau) * norm.cdf(d1) / (S_arr[:, j] * sigma_imp * sqrtT)

    return deltas, gammas

  deltas, gammas = compute_delta_gamma(S_paths, taus)

  dS = np.diff(S_paths, axis=1)
  dollar_gamma = 0.5 * gammas[:, :-1] * dS**2
  theta_bleed = 0.5  *gammas[:, :-1] * sigma_imp**2 * S_paths[:, :-1]**2 * dt
  step_pnl = dollar_gamma - theta_bleed

  cum_pnl = np.cumsum(step_pnl, axis=1)

  return {'S_paths': S_paths, "deltas": deltas, "gammas": gammas, "cum_pnl": cum_pnl, "times": times}

results = simulate_greeks_path(S0=100, K=100, T=1, r=0.05, sigma_imp=0.2, n_steps=252, n_paths=5000)
print(f"Mean total PnL: {results['cum_pnl'][:, -1].mean():.4f}")
print(f"Std total PnL: {results['cum_pnl'][:, -1].std():.4f}")

