# -*- coding: utf-8 -*-
"""Dealer Hedging Mechanics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm

def greek_ladder_pnl(S, K, T, r, sigma, q=0.0,
                     dS=0.0, dsigma=0.0, dt=1/365,
                     option_type='call', position=1.0):

    def compute_all_greeks(S_, K_, T_, r_, sigma_, q_):
        tau = T_
        if tau < 1e-8:
            return None
        sqrtT = np.sqrt(tau)
        d1 = (np.log(S_ / K_) + (r_ - q_ + 0.5 * sigma_**2) * tau) / (sigma_ * sqrtT)
        d2 = d1 - sigma_ * sqrtT
        nd1 = norm.pdf(d1)
        Nd1 = norm.cdf(d1)
        Nd2 = norm.cdf(d2)
        disc_q = np.exp(-q_ * tau)
        disc_r = np.exp(-r_ * tau)

        if option_type == 'call':
            price = S_ * disc_q * Nd1 - K_ * disc_r * Nd2
            delta = disc_q * Nd1
            rho_ = K_ * tau * disc_r * Nd2 / 100
        else:
            price = K_ * disc_r * norm.cdf(-d2) - S_ * disc_q * norm.cdf(-d1)
            delta = -disc_q * norm.cdf(-d1)
            rho_ = -K_ * tau * disc_r * norm.cdf(-d2) / 100

        gamma = disc_q * nd1 / (S_ * sigma_ * sqrtT)
        vega = S_ * disc_q * nd1 * sqrtT / 100
        theta = (-(S_ * disc_q * nd1 * sigma_) / (2 * sqrtT)
                 - r_ * K_ * disc_r * Nd2 if option_type == 'call'
                 else -(S_ * disc_q * nd1 * sigma_) / (2 * sqrtT)
                 + r_ * K_ * disc_r * norm.cdf(-d2)) / 365

        vanna = -disc_q * nd1 * d2 / sigma_
        volga = vega * 100 * d1 * d2 / sigma_
        speed = -gamma / S_ * (d1 / (sigma_ * sqrtT) + 1)

        return dict(price=price, delta=delta, gamma=gamma, vega=vega,
                    theta=theta, rho=rho_, vanna=vanna, volga=volga,
                    speed=speed, d1=d1, d2=d2)

    g = compute_all_greeks(S, K, T, r, sigma, q)

    pnl_delta = position * g['delta'] * dS
    pnl_vega = position * g['vega'] * dsigma * 100
    pnl_theta = position * g['theta'] * dt * 365
    pnl_rho = position * g['rho'] * 0

    pnl_gamma = position * 0.5 * g['gamma'] * dS**2
    pnl_vanna = position * g['vanna'] * dS * dsigma
    pnl_volga = position * 0.5 * (g['volga'] / 100) * dsigma**2

    total_approx = pnl_delta + pnl_vega + pnl_theta + pnl_gamma + pnl_vanna + pnl_volga

    g_new = compute_all_greeks(S + dS, K, T - dt, r, sigma + dsigma, q)
    true_pnl = position * (g_new['price'] - g['price']) if g_new else None

    return {
        'delta_pnl': pnl_delta,
        'gamma_pnl': pnl_gamma,
        'vega_pnl': pnl_vega,
        'theta_pnl': pnl_theta,
        'vanna_pnl': pnl_vanna,
        'volga_pnl': pnl_volga,
        'total_approx': total_approx,
        'true_pnl': true_pnl,
        'greeks': g
    }

result = greek_ladder_pnl(
    S=100, K=100, T=0.25, r=0.05, sigma=0.20, q=0.0,
    dS=2.0, dsigma=0.01, dt=1/365, option_type='call', position=100
)

print("\n=== Greek Ladder P&L Attribution ===")
for k, v in result.items():
    if k != 'greeks' and v is not None:
        print(f"{k:20s}: ${v:8.4f}")

print(f"\nApproximation Error: ${result['total_approx'] - result['true_pnl']:.6f}")

