# -*- coding: utf-8 -*-
"""Long Straddle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def bs_call(S, K, r, q, T, sigma):
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

def bs_put(S, K, r, q, T, sigma):
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1)

# Parameters
S0, K, r, q, T, sigma = 100, 100, 0.05, 0.0, 0.25, 0.20

# Premium paid
C0 = bs_call(S0, K, r, q, T, sigma)
P0 = bs_put(S0, K, r, q, T, sigma)
total_premium = C0 + P0
print(f"Call premium : {C0:.4f}")
print(f"Put premium : {P0:.4f}")
print(f"Total premium : {total_premium:.4f}")
print(f"Upper BE : {K + total_premium:.4f}")
print(f"Lower BE : {K - total_premium:.4f}")
print(f"BE move : {total_premium / S0 * 100:.2f}%")
print(f"Approx BE : {0.7979 * sigma * np.sqrt(T) * 100:.2f}%")

# Expiry payoff
S_range = np.linspace(70, 130, 500)
payoff = np.abs(S_range - K)
pnl = payoff - total_premium

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(S_range, pnl, 'b-', linewidth=2.5, label='P&L at Expiry')
axes[0].plot(S_range, payoff, 'g--', linewidth=1.5, label='Gross Payoff')
axes[0].axhline(0, color='k', linestyle='-', linewidth=0.8)
axes[0].axvline(K, color='gray', linestyle='--', linewidth=1, label=f'Strike K={K}')
axes[0].axvline(K + total_premium, color='r', linestyle=':', label='Upper BE')
axes[0].axvline(K - total_premium, color='r', linestyle=':', label='Lower BE')
axes[0].fill_between(S_range, pnl, 0, where=(pnl > 0), alpha=0.15, color='green', label='Profit Region')
axes[0].fill_between(S_range, pnl, 0, where=(pnl < 0), alpha=0.15, color='red', label='Loss Region')
axes[0].set_xlabel('Underlying Price $S_T$')
axes[0].set_ylabel('P&L')
axes[0].set_title('Long Straddle Expiry P&L')
axes[0].legend(fontsize=8)
axes[0].grid(True, alpha=0.3)

# Value surface for different maturities
for t_remaining in [T, T * 0.75, T * 0.5, T * 0.25, 0.001]:
    if t_remaining < 0.001:
        t_remaining = 1e-6
    val = bs_call(S_range, K, r, q, t_remaining, sigma) + bs_put(S_range, K, r, q, t_remaining, sigma)
    label = f'{t_remaining / T * 100:.0f}% time remaining'
    axes[1].plot(S_range, val - total_premium, label=label, linewidth=1.8)

axes[1].axhline(0, color='k', linewidth=0.8)
axes[1].set_xlabel('Underlying Price $S$')
axes[1].set_ylabel('P&L')
axes[1].set_title('Long Straddle P&L at Different Times to Expiry')
axes[1].legend(fontsize=8)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('long_straddle.png', dpi=150, bbox_inches='tight')
plt.show()

