# -*- coding: utf-8 -*-
"""Short Straddle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.optimize import brentq

def bs_price(S, K, r, q, T, sigma, flag='call'):
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if flag == 'call':
        return S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    else:
        return K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1)

def delta_strike(S, delta, r, q, T, sigma, flag='call'):
    """ Find strike for given delta target. """
    sign = 1 if flag == 'call' else -1
    def f(K):
        d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
        return np.exp(-q * T) * norm.cdf(sign * d1) - abs(delta)
    return brentq(f, S * 0.5, S * 2.0)

# Parameters
S0, r, q, T, sigma = 100, 0.05, 0.0, 0.25, 0.20

# Straddle
C_std = bs_price(S0, S0, r, q, T, sigma, 'call')
P_std = bs_price(S0, S0, r, q, T, sigma, 'put')
straddle_prem = C_std + P_std

# 25-delta strangle
K_C25 = delta_strike(S0, 0.25, r, q, T, sigma, 'call')
K_P25 = delta_strike(S0, 0.25, r, q, T, sigma, 'put')
C_str = bs_price(S0, K_C25, r, q, T, sigma, 'call')
P_str = bs_price(S0, K_P25, r, q, T, sigma, 'put')
strangle_prem = C_str + P_str

print("=== Straddle ===")
print(f"Strike: {S0:.2f}")
print(f"Premium: {straddle_prem:.4f} ({straddle_prem / S0 * 100:.2f}% of S)")
print(f"Lower BE: {S0 - straddle_prem:.4f}")
print(f"Upper BE: {S0 + straddle_prem:.4f}")
print(f"\n=== 25-Delta Strangle ===")
print(f"Put Strike: {K_P25:.4f} (delta = -0.25)")
print(f"Call Strike: {K_C25:.4f} (delta = +0.25)")
print(f"Premium: {strangle_prem:.4f} ({strangle_prem / S0 * 100:.2f}% of S)")
print(f"Lower BE: {K_P25 - strangle_prem:.4f}")
print(f"Upper BE: {K_C25 + strangle_prem:.4f}")
print(f"\nStrangle / Straddle premium ratio: {strangle_prem / straddle_prem:.3f}")

# Compare payoff profiles
S_range = np.linspace(70, 130, 500)
pnl_strad = np.abs(S_range - S0) - straddle_prem
pnl_stran = (np.maximum(S_range - K_C25, 0) + np.maximum(K_P25 - S_range, 0)) - strangle_prem

plt.figure(figsize=(10, 5))
plt.plot(S_range, pnl_strad, 'b-', lw=2.5, label=f'Straddle K={S0}')
plt.plot(S_range, pnl_stran, 'r--', lw=2.5, label=f'Strangle [{K_P25:.1f}, {K_C25:.1f}]')
plt.axhline(0, color='k', lw=0.8)
plt.fill_between(S_range, pnl_strad, 0, where=(pnl_strad > 0), alpha=0.1, color='blue')
plt.fill_between(S_range, pnl_stran, 0, where=(pnl_stran > 0), alpha=0.1, color='red')
plt.xlabel('$S_T$')
plt.ylabel('P&L')
plt.grid(alpha=0.3)
plt.title('Straddle vs. 25-Delta Strangle Expiry P&L')
plt.legend()
plt.tight_layout()
plt.savefig('strangle_vs_straddle.png', dpi=150, bbox_inches='tight')
plt.show()

