# -*- coding: utf-8 -*-
"""Short Straddle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
from scipy.stats import norm

class ShortStraddleMonitor:
    def __init__(self, S0, K, r, q, T, sigma_iv, notional=1e6):
        self.K = K
        self.r = r
        self.q = q
        self.T = T
        self.sigma_iv = sigma_iv
        self.notional = notional

        d1 = (np.log(S0 / K) + (r - q + 0.5 * sigma_iv ** 2) * T) / (sigma_iv * np.sqrt(T))
        d2 = d1 - sigma_iv * np.sqrt(T)
        self.C0 = S0 * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
        self.P0 = K * np.exp(-r * T) * norm.cdf(-d2) - S0 * np.exp(-q * T) * norm.cdf(-d1)
        self.premium_received = self.C0 + self.P0

    def compute_greeks(self, S, tau, sigma=None):
        if sigma is None:
            sigma = self.sigma_iv
        eps = 1e-10
        tau = max(tau, eps)
        K, r, q = self.K, self.r, self.q
        d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * tau) / (sigma * np.sqrt(tau))
        d2 = d1 - sigma * np.sqrt(tau)

        delta = np.exp(-q * tau) * (2 * norm.cdf(d1) - 1)
        gamma = np.exp(-q * tau) * norm.pdf(d1) / (S * sigma * np.sqrt(tau))
        vega = 2 * S * np.exp(-q * tau) * norm.pdf(d1) * np.sqrt(tau)

        theta_call = (-S * np.exp(-q * tau) * norm.pdf(d1) * sigma / (2 * np.sqrt(tau))
                      - r * K * np.exp(-r * tau) * norm.cdf(d2)
                      + q * S * np.exp(-q * tau) * norm.cdf(d1))

        theta_put = (-S * np.exp(-q * tau) * norm.pdf(d1) * sigma / (2 * np.sqrt(tau))
                     + r * K * np.exp(-r * tau) * norm.cdf(-d2)
                     - q * S * np.exp(-q * tau) * norm.cdf(-d1))

        theta = theta_call + theta_put
        return {
            'delta': -delta,
            'gamma': -2 * gamma,
            'vega': -vega,
            'theta': theta
        }

    def pnl_and_risk_report(self, S_current, tau_current, sigma_current):
        K, r, q = self.K, self.r, self.q
        d1 = (np.log(S_current / K) + (r - q + 0.5 * sigma_current ** 2) * tau_current) / (sigma_current * np.sqrt(tau_current))
        d2 = d1 - sigma_current * np.sqrt(tau_current)
        C = S_current * np.exp(-q * tau_current) * norm.cdf(d1) - K * np.exp(-r * tau_current) * norm.cdf(d2)
        P = K * np.exp(-r * tau_current) * norm.cdf(-d2) - S_current * np.exp(-q * tau_current) * norm.cdf(-d1)

        straddle_value = C + P
        pnl = self.premium_received - straddle_value
        greeks = self.compute_greeks(S_current, tau_current, sigma_current)

        print("=" * 50)
        print(" SHORT STRADDLE RISK REPORT ")
        print("=" * 50)
        print(f"Spot: {S_current:.2f}")
        print(f"Strike: {K:.2f}")
        print(f"Tau: {tau_current:.4f} years")
        print(f"IV (current): {sigma_current * 100:.2f}%")
        print(" " * 50)
        print(f"Straddle MtM: {straddle_value:.4f}")
        print(f"Premium Rcvd: {self.premium_received:.4f}")
        print(f"Current P&L: {pnl:.4f} ({pnl / self.premium_received * 100:.1f}% of premium)")
        print(" " * 50)
        print(f"Delta (pos): {greeks['delta']:+.4f}")
        print(f"Gamma (pos): {greeks['gamma']:+.6f}")
        print(f"Vega (pos): {greeks['vega']:+.4f} per vol pt")
        print(f"Theta (pos): {greeks['theta']:+.4f} per day")
        print(" " * 50)

        for vol_shock in [-0.05, -0.03, 0, 0.03, 0.05, 0.10]:
            sig_new = sigma_current + vol_shock
            d1n = (np.log(S_current / K) + (r - q + 0.5 * sig_new ** 2) * tau_current) / (sig_new * max(np.sqrt(tau_current), 1e-10))
            d2n = d1n - sig_new * np.sqrt(tau_current)
            Cn = S_current * np.exp(-q * tau_current) * norm.cdf(d1n) - K * np.exp(-r * tau_current) * norm.cdf(d2n)
            Pn = K * np.exp(-r * tau_current) * norm.cdf(-d2n) - S_current * np.exp(-q * tau_current) * norm.cdf(-d1n)
            pnl_shock = self.premium_received - (Cn + Pn)
            print(f"Vol {vol_shock * 100:+.0f}%: P&L = {pnl_shock:.4f} ({pnl_shock / self.premium_received * 100:.1f}%)")
        print("=" * 50)

monitor = ShortStraddleMonitor(S0=100, K=100, r=0.05, q=0.0, T=0.25, sigma_iv=0.20)
monitor.pnl_and_risk_report(S_current=102, tau_current=0.20, sigma_current=0.21)

