# -*- coding: utf-8 -*-
"""Short Strangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.optimize import brentq

def bs_greeks(S, K, r, q, T, sigma, flag='call'):
    """ Return price and all first-order greeks. """
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if flag == 'call':
        price = S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
        delta = np.exp(-q * T) * norm.cdf(d1)
    else:
        price = K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1)
        delta = -np.exp(-q * T) * norm.cdf(-d1)

    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)

    theta_call = (-S * np.exp(-q * T) * norm.pdf(d1) * sigma / (2 * np.sqrt(T))
                  - r * K * np.exp(-r * T) * norm.cdf(d2)
                  + q * S * np.exp(-q * T) * norm.cdf(d1))

    theta_put = (-S * np.exp(-q * T) * norm.pdf(d1) * sigma / (2 * np.sqrt(T))
                 + r * K * np.exp(-r * T) * norm.cdf(-d2)
                 - q * S * np.exp(-q * T) * norm.cdf(-d1))

    theta = theta_call if flag == 'call' else theta_put
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega, 'theta': theta}

# Parameters
S0, r, q, T, sigma = 100, 0.05, 0.0, 1/12, 0.20

# 25-delta strangle
def find_delta_strike(target_delta, flag):
    def f(K):
        g = bs_greeks(S0, K, r, q, T, sigma, flag)
        return abs(g['delta']) - abs(target_delta)
    return brentq(f, S0 * 0.5, S0 * 2)

K_C = find_delta_strike(0.25, 'call')
K_P = find_delta_strike(0.25, 'put')

call_g = bs_greeks(S0, K_C, r, q, T, sigma, 'call')
put_g = bs_greeks(S0, K_P, r, q, T, sigma, 'put')
total_prem = call_g['price'] + put_g['price']

print("Short 25-Delta Strangle")
print(f"K_C = {K_C:.3f}, C = {call_g['price']:.4f}")
print(f"K_P = {K_P:.3f}, P = {put_g['price']:.4f}")
print(f"Total credit = {total_prem:.4f}")
print(f"Upper BE = {K_C + total_prem:.4f}")
print(f"Lower BE = {K_P - total_prem:.4f}")
print(f"Net Delta = {-(call_g['delta'] - put_g['delta']):.4f}")
print(f"Net Gamma = {-(call_g['gamma'] + put_g['gamma']):.6f}")
print(f"Net Vega = {-(call_g['vega'] + put_g['vega']):.4f}")
print(f"Net Theta = {call_g['theta'] + put_g['theta']:.4f}/day")

# P&L surface across spot and time
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
S_range = np.linspace(80, 125, 400)

# Expiry P&L
expiry_payoff = -(np.maximum(S_range - K_C, 0) + np.maximum(K_P - S_range, 0))
expiry_pnl = expiry_payoff + total_prem
axes[0].plot(S_range, expiry_pnl, 'b-', lw=2.5, label='Expiry P&L')
axes[0].axhline(0, color='k', lw=0.8)
axes[0].axvline(K_P, color='r', ls=':', lw=1.5, label=f'K_P = {K_P:.1f}')
axes[0].axvline(K_C, color='g', ls=':', lw=1.5, label=f'K_C = {K_C:.1f}')
axes[0].fill_between(S_range, expiry_pnl, 0, where=(expiry_pnl > 0), alpha=0.2, color='green')
axes[0].fill_between(S_range, expiry_pnl, 0, where=(expiry_pnl < 0), alpha=0.2, color='red')
axes[0].set_title('Short Strangle: Expiry P&L')
axes[0].set_xlabel('$S_T$')
axes[0].set_ylabel('P&L')
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3)

# Gamma profile across spot
gammas = [-(bs_greeks(s, K_C, r, q, T, sigma, 'call')['gamma'] +
            bs_greeks(s, K_P, r, q, T, sigma, 'put')['gamma']) for s in S_range]
axes[1].plot(S_range, gammas, 'r-', lw=2.5)
axes[1].axhline(0, color='k', lw=0.8)
axes[1].axvline(K_P, color='b', ls=':', lw=1.5)
axes[1].axvline(K_C, color='b', ls=':', lw=1.5)
axes[1].set_title('Gamma Profile vs. Spot')
axes[1].set_xlabel('S')
axes[1].set_ylabel('Gamma (short = negative)')
axes[1].grid(alpha=0.3)

# P&L for different days remaining
for days in [30, 21, 14, 7, 1]:
    tau = days / 252
    vals = [-(bs_greeks(s, K_C, r, q, tau, sigma, 'call')['price'] +
              bs_greeks(s, K_P, r, q, tau, sigma, 'put')['price']) + total_prem for s in S_range]
    axes[2].plot(S_range, vals, lw=1.8, label=f'{days}d remaining')

axes[2].axhline(0, color='k', lw=0.8)
axes[2].set_title('P&L at Different Times to Expiry')
axes[2].set_xlabel('S')
axes[2].set_ylabel('P&L')
axes[2].legend(fontsize=8)
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('short_strangle.png', dpi=150, bbox_inches='tight')
plt.show()

