# -*- coding: utf-8 -*-
"""Calendar Spread Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def bs_call(S, K, r, q, T, sigma):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

def bs_call_greeks(S, K, r, q, T, sigma):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    price = S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    delta = np.exp(-q * T) * norm.cdf(d1)
    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)
    theta = (-S * np.exp(-q * T) * norm.pdf(d1) * sigma / (2 * np.sqrt(T))
             - r * K * np.exp(-r * T) * norm.cdf(d2)
             + q * S * np.exp(-q * T) * norm.cdf(d1))
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega, 'theta': theta}

# Parameters (event calendar scenario)
S0, K, r, q = 100, 100, 0.05, 0.0
T1 = 1/12   # 1-month (post-event)
T2 = 3/12   # 3-month
sig1 = 0.40 # Elevated due to event
sig2 = 0.25 # Normal vol

# Forward vol computation
fwd_var = sig2**2 * T2 - sig1**2 * T1
fwd_vol = np.sqrt(max(fwd_var, 0) / (T2 - T1))
print(f"Near-term IV: {sig1*100:.1f}%")
print(f"Far-term IV: {sig2*100:.1f}%")
print(f"Forward vol: {fwd_vol*100:.2f}%")

# Calendar pricing
near = bs_call_greeks(S0, K, r, q, T1, sig1)
far = bs_call_greeks(S0, K, r, q, T2, sig2)
net_debit = far['price'] - near['price']
print(f"\nNear call: {near['price']:.4f}")
print(f"Far call: {far['price']:.4f}")
print(f"Net debit: {net_debit:.4f}")
print(f"\nCalendar Greeks:")
print(f"Delta: {far['delta'] - near['delta']:+.4f}")
print(f"Gamma: {far['gamma'] - near['gamma']:+.6f} (NEGATIVE = risky)")
print(f"Vega: {far['vega'] - near['vega']:+.4f} (per vol pt)")
print(f"Theta: {far['theta'] - near['theta']:+.4f} (per day, POSITIVE)")

# P&L profile at T1 expiry under different post-event vols
S_range = np.linspace(80, 125, 400)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for sig_post in [0.15, 0.20, 0.25, 0.30, 0.40]:
    tau_remaining = T2 - T1
    residual_val = np.array([bs_call(s, K, r, q, tau_remaining, sig_post) for s in S_range])
    near_expire = np.maximum(S_range - K, 0)
    pnl = residual_val - near_expire - net_debit
    axes[0].plot(S_range, pnl, lw=1.8, label=f'Post-event IV = {sig_post*100:.0f}%')

axes[0].axhline(0, color='k', lw=0.8)
axes[0].axvline(K, color='gray', ls='--', lw=1)
axes[0].set_title('Calendar Spread P&L at T1 Expiry')
axes[0].set_xlabel('$S_{T_1}$')
axes[0].set_ylabel('P&L')
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3)

# Theta decay comparison
taus = np.linspace(0.001, T2, 200)
theta_near = [bs_call_greeks(S0, K, r, q, t, sig1)['theta'] for t in taus]
theta_far = [bs_call_greeks(S0, K, r, q, t, sig2)['theta'] for t in taus]
theta_cal = [f - n for f, n in zip(theta_far, theta_near)]
axes[1].plot(taus*252, theta_near, 'r-', lw=2, label='Near-term theta')
axes[1].plot(taus*252, theta_far, 'b-', lw=2, label='Far-term theta')
axes[1].plot(taus*252, theta_cal, 'g--', lw=2.5, label='Calendar (net theta)')
axes[1].axhline(0, color='k', lw=0.8)
axes[1].set_title('Theta Decay Profile')
axes[1].set_xlabel('Days to Expiry')
axes[1].set_ylabel('Theta')
axes[1].legend(fontsize=8)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('calendar_spread.png', dpi=150, bbox_inches='tight')
plt.show()

