# -*- coding: utf-8 -*-
"""Diagonal Spread Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def bs_call_full(S, K, r, q, T, sigma):
    """ Returns price and greeks for a call. """
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    price = S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

    delta = np.exp(-q * T) * norm.cdf(d1)
    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)
    theta = (-S * np.exp(-q * T) * norm.pdf(d1) * sigma / (2 * np.sqrt(T))
             - r * K * np.exp(-r * T) * norm.cdf(d2)
             + q * S * np.exp(-q * T) * norm.cdf(d1))
    vanna = -np.exp(-q * T) * norm.pdf(d1) * d2 / sigma
    volga = vega * d1 * d2 / sigma
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega,
            'theta': theta, 'vanna': vanna, 'volga': volga}

# Diagonal Spread Parameters
# Buy 6M call at K=100, Sell 1M call at K=105 (bull diagonal)
S0 = 100
r, q = 0.05, 0.0

# Implied vol with smile (simple skew model)
def implied_vol(K, T, S=100, atm_vol=0.20, skew=-0.02):
    """ Simple linear skew model: sigma(K,T) = atm_vol + skew * log(K/S) """
    return atm_vol + skew * np.log(K / S)

K_back, T_back = 100, 6/12   # Long back month
K_front, T_front = 105, 1/12 # Short front month

sig_back = implied_vol(K_back, T_back)
sig_front = implied_vol(K_front, T_front)

back = bs_call_full(S0, K_back, r, q, T_back, sig_back)
front = bs_call_full(S0, K_front, r, q, T_front, sig_front)

net = {k: back[k] - front[k] for k in back}
print(f"Diagonal Spread (Buy 6M K={K_back}, Sell 1M K={K_front})")
print(f"Back IV = {sig_back*100:.1f}%, Front IV = {sig_front*100:.1f}%")
print(f"\nNet Debit: {net['price']:.4f}")
print(f"Net Delta: {net['delta']:+.4f}")
print(f"Net Gamma: {net['gamma']:+.6f}")
print(f"Net Vega: {net['vega']:+.4f}")
print(f"Net Theta: {net['theta']:+.4f}/day")
print(f"Net Vanna: {net['vanna']:+.6f}")
print(f"Net Volga: {net['volga']:+.6f}")

S_range = np.linspace(85, 120, 400)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for atm_vol_shift in [-0.04, -0.02, 0, 0.02, 0.04]:
    tau_remaining = T_back - T_front
    residual = np.array([
        bs_call_full(s, K_back, r, q, tau_remaining,
                     max(implied_vol(K_back, tau_remaining, s, 0.20 + atm_vol_shift), 0.01))['price']
        for s in S_range
    ])
    front_expiry = np.maximum(S_range - K_front, 0)
    pnl = residual - front_expiry - net['price']
    axes[0].plot(S_range, pnl, lw=1.8, label=f'IV shift {atm_vol_shift*100:+.0f}%')

axes[0].axhline(0, color='k', lw=0.8)
axes[0].axvline(K_back, color='b', ls=':', lw=1, label=f'Back K={K_back}')
axes[0].axvline(K_front, color='r', ls=':', lw=1, label=f'Front K={K_front}')
axes[0].set_title('Bull Diagonal: P&L at Front Expiry')
axes[0].set_xlabel('$S_{T_1}$')
axes[0].set_ylabel('P&L')
axes[0].legend(fontsize=7)
axes[0].grid(alpha=0.3)

# Sensitivity to skew
S_range2 = np.linspace(85, 120, 400)
for skew in [-0.04, -0.02, 0, 0.02, 0.04]:
    tau_remaining = T_back - T_front
    residual = np.array([
        bs_call_full(s, K_back, r, q, tau_remaining,
                     max(implied_vol(K_back, tau_remaining, s, 0.20, skew), 0.01))['price']
        for s in S_range2
    ])
    front_expiry = np.maximum(S_range2 - K_front, 0)
    pnl = residual - front_expiry - net['price']
    axes[1].plot(S_range2, pnl, lw=1.8, label=f'Skew = {skew:.2f}')

axes[1].axhline(0, color='k', lw=0.8)
axes[1].set_title('Bull Diagonal: P&L Sensitivity to Skew')
axes[1].set_xlabel('$S_{T_1}$')
axes[1].set_ylabel('P&L')
axes[1].legend(fontsize=7)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('diagonal_spread.png', dpi=150, bbox_inches='tight')
plt.show()

