# -*- coding: utf-8 -*-
"""Risk-Neutral Density Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, lognorm
from scipy.interpolate import CubicSpline

def bs_call(S, K, r, q, T, sigma):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

# Vol surface (with smile using SVI-like parameterization)
def svi_vol(k, a=0.04, b=0.1, rho=-0.3, m=0, sigma_svi=0.3):
    """ Simple SVI: total variance w = a + b*(rho*(k-m) + sqrt((k-m)^2+sigma^2)) """
    w = a + b * (rho * (k - m) + np.sqrt((k - m)**2 + sigma_svi**2))
    return np.sqrt(max(w, 1e-8))

# Parameters
S0, r, q, T = 100, 0.05, 0.0, 0.25
F = S0 * np.exp((r - q) * T)

# Strike grid
K_grid = np.linspace(70, 135, 300)
k_grid = np.log(K_grid / F)

# Implied vols with smile
sigmas = np.array([svi_vol(k) for k in k_grid])

# Call prices
calls = np.array([bs_call(S0, K, r, q, T, sig) for K, sig in zip(K_grid, sigmas)])

# Numerical second derivative (Breeden-Litzenberger)
dK = K_grid[1] - K_grid[0]
rnd = np.exp(r * T) * np.gradient(np.gradient(calls, K_grid), K_grid)

# Lognormal benchmark (flat vol)
sigma_flat = 0.20
rnd_lognorm = lognorm.pdf(K_grid, s=sigma_flat * np.sqrt(T), scale=F * np.exp(-0.5 * sigma_flat**2 * T))

# Butterfly prices (finite difference approximation)
delta_K = 3.0 # Wing width
fly_prices = np.array([
    bs_call(S0, K - delta_K, r, q, T, svi_vol(np.log((K - delta_K) / F)))
    - 2 * bs_call(S0, K, r, q, T, svi_vol(np.log(K / F)))
    + bs_call(S0, K + delta_K, r, q, T, svi_vol(np.log((K + delta_K) / F)))
    for K in K_grid[10:-10]
])
K_fly = K_grid[10:-10]
rnd_from_fly = np.exp(r * T) * fly_prices / delta_K**2

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Vol smile
axes[0].plot(K_grid, sigmas * 100, 'b-', lw=2.5, label='SVI Smile')
axes[0].axhline(sigma_flat * 100, color='r', ls='--', label='Flat vol')
axes[0].set_title('Implied Volatility Smile')
axes[0].set_xlabel('Strike K')
axes[0].set_ylabel('IV (%)')
axes[0].legend()
axes[0].grid(alpha=0.3)

# Risk-neutral density
axes[1].plot(K_grid, rnd, 'b-', lw=2.5, label='RND (Breeden-Litzenberger)')
axes[1].plot(K_grid, rnd_lognorm, 'r--', lw=1.5, label='Lognormal (flat vol)')
axes[1].fill_between(K_grid, rnd, 0, alpha=0.2, color='blue')
axes[1].set_title('Risk-Neutral Density')
axes[1].set_xlabel('$S_T$')
axes[1].set_ylabel('Density')
axes[1].legend(fontsize=8)
axes[1].grid(alpha=0.3)

# Butterfly prices
axes[2].bar(K_fly, fly_prices, width=2.0, color='steelblue', alpha=0.7, label=f'Butterfly price (wings {delta_K})')
axes[2].set_title(f'Butterfly Prices (Wing = {delta_K})')
axes[2].set_xlabel('Body Strike K')
axes[2].set_ylabel('Butterfly Price')
axes[2].legend(fontsize=8)
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('butterfly_rnd.png', dpi=150, bbox_inches='tight')
plt.show()

# Detailed butterfly P&L
K1, K2, K3 = 95, 100, 105
sig1 = svi_vol(np.log(K1 / F))
sig2 = svi_vol(np.log(K2 / F))
sig3 = svi_vol(np.log(K3 / F))
C1 = bs_call(S0, K1, r, q, T, sig1)
C2 = bs_call(S0, K2, r, q, T, sig2)
C3 = bs_call(S0, K3, r, q, T, sig3)
fly_debit = C1 - 2 * C2 + C3

print(f"\nButterfly: K=[{K1}, {K2}, {K3}]")
print(f"Call prices: {C1:.4f}, {C2:.4f}, {C3:.4f}")
print(f"Net debit: {fly_debit:.4f}")
print(f"Max profit: {K2 - K1 - fly_debit:.4f} (at S_T = {K2})")
print(f"Lower BE: {K1 + fly_debit:.4f}")
print(f"Upper BE: {K3 - fly_debit:.4f}")
print(f"Implied prob (S~{K2}): {fly_debit / (K2 - K1) * np.exp(r * T) * 100:.2f}%")

