# -*- coding: utf-8 -*-
"""Iron Condor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.optimize import brentq

def bs_price_greeks(S, K, r, q, T, sigma, flag):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if flag == 'call':
        price = S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
        delta = np.exp(-q * T) * norm.cdf(d1)
    else:
        price = K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1)
        delta = -np.exp(-q * T) * norm.cdf(-d1)
    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)
    theta = (-S * np.exp(-q * T) * norm.pdf(d1) * sigma / (2 * np.sqrt(T))
             + (-1 if flag == 'call' else 1) * (-r * K * np.exp(-r * T) *
             (norm.cdf(d2) if flag == 'call' else norm.cdf(-d2))
             + q * S * np.exp(-q * T) *
             (norm.cdf(d1) if flag == 'call' else norm.cdf(-d1))))
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega, 'theta': theta}

def find_delta_strike(S, target_delta, r, q, T, sigma, flag):
    def f(K):
        g = bs_price_greeks(S, K, r, q, T, sigma, flag)
        return abs(g['delta']) - abs(target_delta)
    return brentq(f, S * 0.5, S * 2)

class IronCondor:
    def __init__(self, S0, r, q, T, sigma, delta_short=0.25, delta_long=0.10):
        self.S0 = S0
        self.r = r
        self.q = q
        self.T = T
        self.sigma = sigma

        # Find strikes
        self.K4 = find_delta_strike(S0, delta_long, r, q, T, sigma, 'call')
        self.K3 = find_delta_strike(S0, delta_short, r, q, T, sigma, 'call')
        self.K2 = find_delta_strike(S0, delta_short, r, q, T, sigma, 'put')
        self.K1 = find_delta_strike(S0, delta_long, r, q, T, sigma, 'put')

        # Leg prices
        self.c3 = bs_price_greeks(S0, self.K3, r, q, T, sigma, 'call')
        self.c4 = bs_price_greeks(S0, self.K4, r, q, T, sigma, 'call')
        self.p2 = bs_price_greeks(S0, self.K2, r, q, T, sigma, 'put')
        self.p1 = bs_price_greeks(S0, self.K1, r, q, T, sigma, 'put')

        # Net credit (selling K2 put, K3 call; buying K1 put, K4 call)
        self.credit = (self.p2['price'] - self.p1['price'] + self.c3['price'] - self.c4['price'])
        self.call_wing = self.K4 - self.K3
        self.put_wing = self.K2 - self.K1
        self.max_loss = max(self.call_wing, self.put_wing) - self.credit
        self.ror = self.credit / self.max_loss

    def report(self):
        print(f"{'='*55}")
        print(f" IRON CONDOR STRUCTURE REPORT ")
        print(f"{'='*55}")
        print(f" Spot = {self.S0:.2f}, T={self.T*252:.0f}d, IV={self.sigma*100:.1f}%")
        print(f"{' '*55}")
        print(f"K1 (long put) : {self.K1:.3f} (delta={self.p1['delta']:.3f})")
        print(f"K2 (short put) : {self.K2:.3f} (delta={self.p2['delta']:.3f})")
        print(f"K3 (short call) : {self.K3:.3f} (delta={self.c3['delta']:.3f})")
        print(f"K4 (long call) : {self.K4:.3f} (delta={self.c4['delta']:.3f})")
        print(f"{' '*55}")
        print(f"Put spread credit : {self.p2['price'] - self.p1['price']:.4f}")
        print(f"Call spread credit : {self.c3['price'] - self.c4['price']:.4f}")
        print(f"Total credit : {self.credit:.4f} ({self.credit/self.S0*100:.2f}%)")
        print(f"Max loss : {self.max_loss:.4f}")
        print(f"Return on Risk : {self.ror*100:.1f}%")
        print(f"Lower BE : {self.K2 - self.credit:.4f}")
        print(f"Upper BE : {self.K3 + self.credit:.4f}")
        print(f"Profit zone width : {self.K3 - self.K2 + 2*self.credit:.4f}")
        print(f"{' '*55}")

        # Net greeks
        delta_net = (-self.c3['delta'] + self.c4['delta'] + self.p2['delta'] - self.p1['delta'])
        gamma_net = (-self.c3['gamma'] + self.c4['gamma'] - self.p2['gamma'] + self.p1['gamma'])
        vega_net = (-self.c3['vega'] + self.c4['vega'] - self.p2['vega'] + self.p1['vega'])
        theta_net = (self.c3['theta'] - self.c4['theta'] + self.p2['theta'] - self.p1['theta'])
        print(f"Net Delta : {delta_net:+.5f}")
        print(f"Net Gamma : {gamma_net:+.7f} (negative)")
        print(f"Net Vega : {vega_net:+.5f} (negative)")
        print(f"Net Theta : {theta_net:+.5f} (positive, /day)")
        print(f"Theta / Vega : {theta_net/abs(vega_net):.5f} (theta earned per vega pt)")
        print(f"{'='*55}")

    def plot_pnl(self):
        S_range = np.linspace(self.K1 * 0.9, self.K4 * 1.1, 500)
        expiry = -(np.maximum(S_range - self.K3, 0)
                  - np.maximum(S_range - self.K4, 0)
                  + np.maximum(self.K2 - S_range, 0)
                  - np.maximum(self.K1 - S_range, 0))
        pnl = expiry + self.credit

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        axes[0].plot(S_range, pnl, 'b-', lw=2.5, label='Iron Condor P&L')
        axes[0].fill_between(S_range, pnl, 0, where=(pnl > 0), alpha=0.2, color='green')
        axes[0].fill_between(S_range, pnl, 0, where=(pnl < 0), alpha=0.2, color='red')
        axes[0].axhline(0, color='k', lw=0.8)
        for K, label in [(self.K1, 'K1'), (self.K2, 'K2'), (self.K3, 'K3'), (self.K4, 'K4')]:
            axes[0].axvline(K, color='gray', ls='--', lw=1, alpha=0.7)
            axes[0].text(K, axes[0].get_ylim()[0]*0.95, label, ha='center', fontsize=8)
        axes[0].set_title('Iron Condor: Expiry P&L')
        axes[0].set_xlabel('$S_T$')
        axes[0].set_ylabel('P&L')
        axes[0].legend()
        axes[0].grid(alpha=0.3)

        # Time decay of P&L
        S_range2 = np.linspace(self.S0 * 0.88, self.S0 * 1.12, 400)
        for days in [30, 21, 14, 7, 1]:
            tau = days / 252
            val = np.array([
                -(bs_price_greeks(s, self.K3, self.r, self.q, tau, self.sigma, 'call')['price']
                  - bs_price_greeks(s, self.K4, self.r, self.q, tau, self.sigma, 'call')['price']
                  + bs_price_greeks(s, self.K2, self.r, self.q, tau, self.sigma, 'put')['price']
                  - bs_price_greeks(s, self.K1, self.r, self.q, tau, self.sigma, 'put')['price'])
                + self.credit
                for s in S_range2
            ])
            axes[1].plot(S_range2, val, lw=1.8, label=f'{days}d')

        axes[1].axhline(0, color='k', lw=0.8)
        axes[1].set_title('Iron Condor: P&L at Different Times to Expiry')
        axes[1].set_xlabel('S')
        axes[1].set_ylabel('P&L')
        axes[1].legend(fontsize=8)
        axes[1].grid(alpha=0.3)

        plt.tight_layout()
        plt.savefig('iron_condor.png', dpi=150, bbox_inches='tight')
        plt.show()

# Run analysis
ic = IronCondor(S0=100, r=0.05, q=0.0, T=30/252, sigma=0.20, delta_short=0.25, delta_long=0.10)
ic.report()
ic.plot_pnl()

