# -*- coding: utf-8 -*-
"""Ratio Spread Analysis and Skew Trading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.optimize import brentq

def bs_call_full(S, K, r, q, T, sigma):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    price = S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    delta = np.exp(-q * T) * norm.cdf(d1)
    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega}

def bs_put_full(S, K, r, q, T, sigma):
    eps = 1e-10
    T = max(T, eps)
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    price = K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1)
    delta = -np.exp(-q * T) * norm.cdf(-d1)
    gamma = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * np.exp(-q * T) * norm.pdf(d1) * np.sqrt(T)
    return {'price': price, 'delta': delta, 'gamma': gamma, 'vega': vega}

S0, r, q, T = 100, 0.05, 0.0, 1/12

# Smile model
def smile_vol(K, S=100, atm=0.20, skew=-0.025, kurt=0.001):
    k = np.log(K / S)
    return atm + skew * k + kurt * k**2

# 1x2 CALL RATIO SPREAD
K1_c, K2_c = 100, 105 # Buy ATM call, sell 2x OTM call
sig1_c = smile_vol(K1_c)
sig2_c = smile_vol(K2_c)
c1 = bs_call_full(S0, K1_c, r, q, T, sig1_c)
c2 = bs_call_full(S0, K2_c, r, q, T, sig2_c)
call_ratio_debit = c1['price'] - 2 * c2['price']

print("1x2 CALL RATIO SPREAD")
print(f"Buy 1 call K={K1_c} IV={sig1_c*100:.2f}%: price={c1['price']:.4f}")
print(f"Sell 2 call K={K2_c} IV={sig2_c*100:.2f}%: price={c2['price']:.4f}")
print(f"Net debit: {call_ratio_debit:.4f}")
print(f"Max profit at K2: {K2_c - K1_c - call_ratio_debit:.4f}")
print(f"Upper BE: {2*K2_c - K1_c - call_ratio_debit:.4f}")
print(f"Net Delta: {c1['delta'] - 2*c2['delta']:+.4f}")
print(f"Net Gamma: {c1['gamma'] - 2*c2['gamma']:+.6f}")
print(f"Net Vega: {c1['vega'] - 2*c2['vega']:+.4f}")

# 1x2 PUT RATIO SPREAD
K2_p, K1_p = 100, 95 # Buy ATM put, sell 2x OTM put
sig2_p = smile_vol(K2_p)
sig1_p = smile_vol(K1_p)
p2 = bs_put_full(S0, K2_p, r, q, T, sig2_p)
p1 = bs_put_full(S0, K1_p, r, q, T, sig1_p)
put_ratio_debit = p2['price'] - 2 * p1['price']

print(f"\n1x2 PUT RATIO SPREAD")
print(f"Buy 1 put K={K2_p} IV={sig2_p*100:.2f}%: price={p2['price']:.4f}")
print(f"Sell 2 put K={K1_p} IV={sig1_p*100:.2f}%: price={p1['price']:.4f}")
print(f"Net debit / credit: {put_ratio_debit:.4f} ({'debit' if put_ratio_debit > 0 else 'credit'})")
print(f"Net Delta: {p2['delta'] - 2*p1['delta']:+.4f}")
print(f"Net Vega: {p2['vega'] - 2*p1['vega']:+.4f}")

# Payoff diagrams
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
S_range = np.linspace(80, 125, 500)

# Call ratio payoff
call_ratio_pnl = (np.maximum(S_range - K1_c, 0) - 2 * np.maximum(S_range - K2_c, 0) - call_ratio_debit)
axes[0].plot(S_range, call_ratio_pnl, 'b-', lw=2.5, label=f'1x2 Call Ratio [{K1_c}, {K2_c}]')
axes[0].axhline(0, color='k', lw=0.8)
axes[0].axvline(K2_c, color='r', ls='--', lw=1, label=f'Max profit K={K2_c}')
axes[0].fill_between(S_range, call_ratio_pnl, 0, where=(call_ratio_pnl > 0), alpha=0.2, color='green')
axes[0].fill_between(S_range, call_ratio_pnl, 0, where=(call_ratio_pnl < 0), alpha=0.2, color='red')
axes[0].set_title('1x2 Call Ratio Spread')
axes[0].set_xlabel('$S_T$')
axes[0].set_ylabel('P&L')
axes[0].legend()
axes[0].grid(alpha=0.3)

# Put ratio payoff
put_ratio_pnl = (np.maximum(K2_p - S_range, 0) - 2 * np.maximum(K1_p - S_range, 0) - put_ratio_debit)
axes[1].plot(S_range, put_ratio_pnl, 'r-', lw=2.5, label=f'1x2 Put Ratio [{K1_p}, {K2_p}]')
axes[1].axhline(0, color='k', lw=0.8)
axes[1].axvline(K1_p, color='b', ls='--', lw=1, label=f'Max profit K={K1_p}')
axes[1].fill_between(S_range, put_ratio_pnl, 0, where=(put_ratio_pnl > 0), alpha=0.2, color='green')
axes[1].fill_between(S_range, put_ratio_pnl, 0, where=(put_ratio_pnl < 0), alpha=0.2, color='red')
axes[1].set_title('1x2 Put Ratio Spread')
axes[1].set_xlabel('$S_T$')
axes[1].set_ylabel('P&L')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('ratio_spreads.png', dpi=150, bbox_inches='tight')
plt.show()

