# -*- coding: utf-8 -*-
"""Realized Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd

def realized_volatility(prices: pd.Series, window: int = 21, annualize: bool = True, trading_days: int = 252) -> pd.Series:
  log_returns = np.log(prices / prices.shift(1))

  rv = log_returns.rolling(window=window).std(ddof=1)

  if annualize:
    rv = rv * np.sqrt(trading_days)

  return rv

def realized_variance_hf(intraday_returns: pd.Series) -> float:
  return (intraday_returns ** 2).sum()

def volatility_signature_plot(intraday_prices: pd.DataFrame, sampling_intervals: list) -> pd.DataFrame:
  results = {}
  for interval in sampling_intervals:
    sampled = intraday_prices.resample(f'{interval}T').last()
    log_ret = np.log(sampled / sampled.shift(1)).dropna()
    daily_rv = (log_ret ** 2).resample('D').sum()
    results[interval] = daily_rv.mean()
  return pd.DataFrame(results, index=['Mean RV']).T

np.random.seed(12)
n = 500
returns_sim = np.random.normal(0.0003, 0.012, n)
prices_sim = pd.Series(100 * np.exp(np.cumsum(returns_sim)), name='SPX_sim')

rv_10 = realized_volatility(prices_sim, window=10)
rv_21 = realized_volatility(prices_sim, window=21)
rv_63 = realized_volatility(prices_sim, window=63)
rv_252 = realized_volatility(prices_sim, window=252)

print(f"Latest 10-day RV: {rv_10.iloc[-1]:.4%}")
print(f"Latest 21-day RV: {rv_21.iloc[-1]:.4%}")
print(f"Latest 63-day RV: {rv_63.iloc[-1]:.4%}")
print(f"Latest 252-day RV: {rv_252.iloc[-1]:.4%}")

