# -*- coding: utf-8 -*-
"""Implied Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.optimize import brentq

def bs_price(S: float, K: float, T: float, r: float, sigma: float, option_type: str = 'call') -> float:
  if T <= 0 or sigma <= 0:
    return max(0.0, S - K) if option_type == 'call' else max(0.0, K - S)

  d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
  d2 = d1 - sigma * np.sqrt(T)

  if option_type == 'call':
    return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

  elif option_type == 'put':
    return K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

def bs_vega(S: float, K: float, T: float, r: float, sigma: float) -> float:
  d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
  return S * np.sqrt(T) * norm.pdf(d1)

def implied_vol_newton(market_price: float, S: float, K: float, T: float, r: float, option_type:str = 'call', max_iter: int = 100, tol: float = 1e-8) -> float:
  sigma = np.sqrt(2 * np.pi/T) * (market_price / S)
  sigma = max(0.001, min(sigma, 5.0))

  for i in range(max_iter):
    price = bs_price(S, K, T, r, sigma, option_type)
    vega = bs_vega(S, K, T, r, sigma)

    if vega < 1e-10:
      break

    diff = price - market_price
    if abs(diff) < tol:
      return sigma

    sigma -= diff / vega
    sigma = max(1e-6, min(sigma, 10.0))

  return sigma

def implied_vol_brentq(market_price: float, S: float, K: float, T: float, r: float, option_type: str = 'call') -> float:
  intrinsic = max(0.0, S - K) if option_type == 'call' else max(0.0, K - S)

  if market_price <= intrinsic:
    raise ValueError("Market Price below intrisic value; no valid IV.")

  f = lambda sigma: bs_price(S, K, T, r, sigma, option_type) - market_price

  try:
    iv = brentq(f, 1e-6, 10.0, xtol=1e-8, full_output=False)
  except ValueError:
    return np.nan

  return iv

S = 4500.0
K = 4400.0
T = 30 / 252
r = 0.05
market_price = 65.0

iv = implied_vol_brentq(market_price, S, K, T, r, option_type='put')
print(f"Implied Volatility: {iv:2%}")

reprice = bs_price(S, K, T, r, iv, 'put')
print(f"BS price at IV: {reprice:.4f} (market: {market_price:.4f})")

