# -*- coding: utf-8 -*-
"""Volatility Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import pandas as pd
import numpy as np
from arch import arch_model

def fit_garch(returns: pd.Series, p: int = 1, q: int = 1, dist: str = 'Normal') -> dict:
  scaled = returns * 100

  model = arch_model(scaled, mean='Constant', vol='GARCH', p=p, q=q, dist=dist)

  result = model.fit(disp='off', options={'maxiter':500})

  params = result.params
  omega = params['omega']
  alpha = params.get('alpha[1]', None)
  beta = params.get('beta[1]', None)

  if alpha is not None and beta is not None:
    alpha_val = float(alpha)
    beta_val = float(beta)

    divisor = (1 - alpha_val - beta_val)
    if divisor > 0:
        long_run_var = float(omega) / divisor
    else:
        long_run_var = None

    if long_run_var:
      long_run_vol_ann = np.sqrt(long_run_var * 252) / 100
    else:
      long_run_vol_ann = None

    sum_alpha_beta = alpha_val + beta_val
    if 0 < sum_alpha_beta < 1:
        half_life = np.log(0.5) / np.log(sum_alpha_beta)
    else:
        half_life = np.inf

  else:
    long_run_vol_ann = None
    half_life = None

  cond_vol_ann = result.conditional_volatility / 100 * np.sqrt(252)

  forecast = result.forecast(horizon=10, reindex=False)
  vol_forecast = np.sqrt(forecast.variance.values[-1]) / 100 * np.sqrt(252)

  print("="*50)
  print("GARCH ({},{})".format(p, q))
  print("="*50)
  print(f"omega: {omega:.6f}")

  if alpha is not None:
    print(f"alpha: {alpha_val:.6f}")
  if beta is not None:
    print(f"beta: {beta_val:.6f}")
  if alpha is not None and beta is not None:
    print(f"persistence: {float(alpha) + float(beta):.6f}")
  print(f"Vol half-life: {half_life:.1f} days" if half_life is not None and half_life != np.inf else "")
  print(f"AIC: {result.aic:.2f}")
  print(f"BIC: {result.bic:.2f}")
  print(f"Loglik: {result.loglikelihood:.2f}")

  return {'result': result, 'params': params, 'cond_vol_ann': pd.Series(cond_vol_ann, index=returns.index), 'vol_forecast': vol_forecast, 'half_life': half_life, 'long_run_vol': long_run_vol_ann}

np.random.seed(12)
omega_true, alpha_true, beta_true = 0.02, 0.08, 0.90
T = 2000
eps = np.zeros(T)
sigma2 = np.zeros(T)
sigma2[0] = omega_true / (1- alpha_true - beta_true)

for t in range(1, T):
  sigma2[t] = omega_true + alpha_true * eps[t-1]**2 + beta_true * sigma2[t-1]
  eps[t] = np.sqrt(sigma2[t]) * np.random.randn()

returns_garch = pd.Series(eps, name='Simulated')
garch_fit = fit_garch(returns_garch, p=1, q=1, dist='Normal')

