# -*- coding: utf-8 -*-
"""Fat Tails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy import stats
import warnings

def tail_analysis(returns: pd.Series, fit_student_t: bool = True) -> dict:
  r = returns.dropna()
  n = len(r)

  mu = r.mean()
  sigma = r.std(ddof=1)
  z = (r - mu) / sigma

  skewness = float(stats.skew(r))
  kurt_excess = float(stats.kurtosis(r))

  jb_start, jb_pval = stats.jarque_bera(r)

  ks_start, ks_pval = stats.kstest(z, cdf=stats.norm.cdf)

  ad_result = stats.anderson(r, dist='norm')

  if n <= 5000:
    sw_stat, sw_pval = stats.shapiro(r)
  else:
    sw_stat, sw_pval = None, None

  print("="*65)
  print(f"Fat Tails Analysis (n={n} observations)")
  print("="*65)
  print(f"Mean (daily): {mu:.6f} ({mu*252:.2%} annualized)")
  print(f"Vol (daily): {sigma:.6f} ({sigma*np.sqrt(252):.2%} annualized)")
  print(f"Skewness: {skewness:.6f} (Normal=0)")
  print(f"Kurtosis: {kurt_excess:.6f} (Normal=0)")
  print(f"Min return: {r.min():.4f} ({r.min() / sigma:.1f} sigma)")
  print(f"Max return: {r.max():.4f} ({r.max() / sigma:.1f} sigma)")
  print()
  print("Normailty Tests:")
  print(f"Jarque-Bera: stat={jb_start:.1f}, p={jb_pval:.2e}")
  print(f"Kolmogorov-Smirnov: stat={ks_start:.1f}, p={ks_pval:.2e}")

  if sw_stat is not None:
    print(f"Shapiro-Wilk: stat={sw_stat:.1f}, p={sw_pval:.4e}")

  results = {'n': n, 'mean':mu, 'std': sigma, 'skewness': skewness, 'excess_kurtosis': kurt_excess, 'jb_stat': jb_start, 'jb_pval': jb_pval, 'ks_stat': ks_start, 'ks_pval': ks_pval}

  if fit_student_t:
    df_t, loc_t, scale_t = stats.t.fit(r, floc=0)
    print(f"\n Student-t Fit:")
    print(f"Degrees of freedom (nu): {df_t:.2f}")
    print(f"Implied excess kurtosis: {6/(df_t-4):.2f}" if df_t > 4 else " nu <= 4: kurtosis is infinite")
    print(f"Scale: {scale_t:.6f}")

    ll_normal = stats.norm.logpdf(r, mu, sigma).sum()
    ll_t = stats.t.logpdf(r, df_t, loc_t, scale_t).sum()

    print(f"\n Log-likelihood (Normal): {ll_normal:.2f}")
    print(f"Log-likelihhod (t-dist): {ll_t:.2f}")
    print(f"Improvement: {ll_t - ll_normal:.2f} (positive = t is better)")

    results['t_df'] = df_t
    results['t_loc'] = loc_t
    results['t_scale'] = scale_t

  print("\n VaR Comparison (1-day, annualized vol):")
  confidence_levels = [0.95, 0.99, 0.999]
  for cl in confidence_levels:
    var_normal = -stats.norm.ppf(1 - cl) * sigma
    if fit_student_t and 't_df' in results:
      var_t = -stats.t.ppf(1 - cl, results['t_df']) * results['t_scale']
    else:
      var_t = None
    print(f" {cl:.1%} VaR -- Normal: {var_normal:.2%}" + (f", Student-t: {var_t:.2%}" if var_t else " "))

  return results

np.random.seed(12)
t_returns = pd.Series(stats.t.rvs(df=4, loc=0, scale=0.012, size=2000), name='Simulated_t4')
analysis = tail_analysis(t_returns)

