# -*- coding: utf-8 -*-
"""Uncertainty Pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from scipy.stats import norm

def compute_var_swap_rate(strikes: np.ndarray, call_prices: np.ndarray, put_prices: np.ndarray, F: float, K0: float, T: float, r: float) -> float:
  prices = np.where(strikes <= K0, put_prices, call_prices)

  n = len(strikes)
  delta_K = np.zeros(n)
  delta_K[0] = strikes[1] - strikes[0]
  delta_K[-1] = strikes[-1] - strikes[-2]
  delta_K[1:-1] = (strikes[2:] - strikes[:-2]) / 2

  integral = np.sum(prices / strikes**2 * delta_K)

  var_swap = (2 * np.exp(r * T) / T) * integral - (1 / T) * (F / K0 - 1) ** 2

  return max(var_swap, 0.0)

S, T, r = 100., 30/365, 0.05
F = S * np.exp(r * T)
K0 = 98.0

strikes = np.array([80, 85, 90, 94, 96, 98, 100, 102, 104, 106, 108, 110, 115, 120])

d1 = (np.log(S/strikes) + (r + 0.5 * 0.18 ** 2) * T) / (0.18 * np.sqrt(T))
d2 = d1 - 0.18 * np.sqrt(T)
calls = S * norm.cdf(d1) - strikes* np.exp(-r*T)*norm.cdf(d2)
puts = strikes* np.exp(-r*T)*norm.cdf(-d2) - S * norm.cdf(-d1)

var_rate = compute_var_swap_rate(strikes, calls, puts, F, K0, T, r)
vix_like = np.sqrt(var_rate) * 100

print(f"Model-free integrateed vol: {vix_like:.2f}%")
print(f"Expected VIX-like value: ^18% (true vol input was 18%)")

