# -*- coding: utf-8 -*-
"""Time Scaling of Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from scipy.stats import linregress

def hurst_exponent(returns: pd.Series, lags: list = None) -> float:
  if lags is None:
    max_lag = len(returns) // 2
    lags = [2**i for i in range(2, int(np.log2(max_lag)) + 1) if 2**i <= max_lag]
    if not lags:
        print("Returns series is too short to compute Hurst exponent with default lags.")
        return np.nan

  log_lags_list = []
  log_rs_list = []

  for lag in lags:
    if lag < 2 or lag > len(returns):
        continue

    rs_per_subseries = []
    n_subs = len(returns) // lag
    for k in range(n_subs):
      sub = returns.iloc[k*lag : (k+1)*lag]
      if len(sub) < 2:
          continue

      mean_adj = sub - sub.mean()
      cumdev = np.cumsum(mean_adj)
      R = cumdev.max() - cumdev.min()
      S = sub.std(ddof=1)

      if S > 0:
        rs_per_subseries.append(R / S)

    if rs_per_subseries:
      mean_rs = np.mean(rs_per_subseries)
      if mean_rs > 0:
          log_lags_list.append(np.log(lag))
          log_rs_list.append(np.log(mean_rs))

  if len(log_lags_list) < 2:
    print("Not enough valid R/S values to perform linear regression for Hurst exponent.")
    return np.nan

  H, intercept, r_val, p_val, se = linregress(log_lags_list, log_rs_list)

  print(f"\nHurst Exponent Estimation (R/S Analysis)")
  print(f"H = {H:.4f}, R^2 = {r_val ** 2:.4f}")
  print(f" Interpretation: ", end="")
  if abs(H - 0.5) < 0.05:
    print(f"Near random walk (H = {H:.2f} \u2248 0.5)")
  elif H > 0.55:
    print(f"Positive trend (H = {H:.2f} > 0.5)")
  else:
    print(f"Negative trend (H = {H:.2f} < 0.5)")

  return H

scales = time_scale_vol(daily_vol=0.20, n_days=252)

np.random.seed(12)
iid_returns = pd.Series(np.random.randn(2000)*0.01)
H_iid = hurst_exponent(iid_returns)

