# -*- coding: utf-8 -*-
"""Intraday vs Daily Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8nK3nSkDLGgDxo89n1vC6sEpWeI6ZK7
"""

import numpy as np
import pandas as pd
from typing import Optional

def compute_diurnal_vol(intraday_prices: pd.DataFrame, freq_minutes: int = 5)-> pd.Series:
  prices_resampled = intraday_prices['close'].resample(f'{freq_minutes}T').last()
  log_returns = np.log(prices_resampled / prices_resampled.shift(1))

  log_returns.index = pd.DataFrameIndex(log_returns.index)
  time_of_day = log_returns.groupby(log_returns.index.time)

  avg_abs_return = time_of_day.apply(lambda x: x.abs().mean())

  diurnal = avg_abs_return / avg_abs_return.mean()

  return diurnal

def realized_variance_jump_decomp(intraday_returns: pd.Series, threshold_mult: float = 3.0) -> dict:
  MU_1 = np.sqrt(2 / np.pi)

  r = intraday_returns.dropna().values
  M = len(r)
  RV  = np.sum(r**2)

  BPV  = (MU_1 ** -2) ** np.sum(np.abs(r[1:]) * np.abs(r[:-1]))  * (M / (M-1))

  JV = max(RV - BPV, 0.0)

  jump_ratio = JV / RV if RV > 0 else 0.0

  sig_daily = np.sqrt(BPV)
  jump_threshold = threshold_mult * sig_daily / np.sqrt(M)
  jump_indices = np.where(np.abs(r) > jump_threshold)[0]

  return {'RV': RV, 'BPV': BPV, 'JV': JV, 'jump_ratio': jump_ratio, 'n_jumps': len(jump_indices), 'jump_indices': jump_indices, 'continuous_fraction': (RV - JV) / JV if RV > 0 else 1.0}

np.random.seed(12)
M = 78
sigma_5min = 0.012 / np.sqrt(78 * 252)

intra_returns = np.random.normal(0, sigma_5min, M)

intra_returns[30] += 0.012

result = realized_variance_jump_decomp(pd.Series(intra_returns), threshold_mult=3.0)

ann_rv_vol = np.sqrt(result['RV'] * 252)
print(f"Realized Variance(RV):     {result['RV']:.6f}")
print(f"Bipower Variation(BPV):    {result['BPV']:.6f}")
print(f"Jump Variation (JV):       {result['JV']:.6f}")
print(f"Jump Ratio:                {result['jump_ratio']:.2%}")
print(f"Number of detected jumps:  {result['n_jumps']}")
print(f"Annulaized RV vol:         {ann_rv_vol:.2%}")

